In [2]:
import sys
import pandas as pd
from pathlib import Path
pd.set_option('display.max_columns', None)
sys.path.append(str(Path.cwd().parent / "src"))
import csv
import numpy
import utils.data_loader as dl
import utils.data_summaries as ds
import utils.standardize_columns as sc

In [3]:
print(dir(dl))
print(dir(ds))
print(dir(sc))

['Path', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'csv', 'get_sources', 'pd', 'pull_data', 'read_files']
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'check_duplicates', 'column_presence', 'compare_columns', 'full_summary', 'pd', 'quick_summary', 'search_df']
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_resolve', 'col_to_bool', 'col_to_cat', 'col_to_date', 'col_to_float', 'col_to_int', 'col_to_snake', 'col_to_str', 'pd', 're']

In [4]:
#Read available datasets available for data source
path = "C:\\Users\\1\\Desktop\\project\\data\\cleaned_data"
DataSources = dl.get_sources(path)
print(DataSources)

[WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/311'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/climate'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/neighbourhoods'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/ward_census'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/watermain_breaks'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/watermains'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/weather')]

## All sheets

### To-be-combined Metric tables
Dwellings and Family data collected for 2011 is stored in the households data, we can combine Dwellings and Family into households and have a households metric data in the structure of 

|Variable|Ward|Year|Value|Category|


Reconvert the transformed wide table back to long and union them

In [5]:
source = DataSources[3]
readable = dl.read_files(source)
readable

CSV
  dwellings_long.csv
  education_long.csv
  ethnic_long.csv
  families_long.csv
  households_long.csv
  income_long.csv
  labour_long.csv
  population_long.csv

[WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/ward_census/dwellings_long.csv'),
 WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/ward_census/education_long.csv'),
 WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/ward_census/ethnic_long.csv'),
 WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/ward_census/families_long.csv'),
 WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/ward_census/households_long.csv'),
 WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/ward_census/income_long.csv'),
 WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/ward_census/labour_long.csv'),
 WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/ward_census/population_long.csv')]

In [6]:
data = dl.pull_data(source)
print(f"number of datasets from source: {len(data)}")
print(f"names of remaining datasets: {data.keys()}")

CSV
  dwellings_long.csv
  education_long.csv
  ethnic_long.csv
  families_long.csv
  households_long.csv
  income_long.csv
  labour_long.csv
  population_long.csv
number of datasets from source: 8
names of remaining datasets: dict_keys(['dwellings_long', 'education_long', 'ethnic_long', 'families_long', 'households_long', 'income_long', 'labour_long', 'population_long'])

### Drop Totals

In [7]:
def drop_totals(df):
    df = df[~df["variable"].str.contains("total", case=False, na=False)] #drop variable containing string "total"
    df = df[~df["geography"].str.contains("toronto", case=False, na=False)].reset_index(drop=True) # drop geography = Toronto
    return df

## Dwellings Transformation 1/8

In [108]:
dwelling = data['dwellings_long']
dwelling[dwelling['geography']=='Ward 1']

,variable,geography,value,year,category
25,Total - Occupied private dwellings by structur...,Ward 1,38135,2021,dwellings
26,Single-detached house,Ward 1,11270,2021,dwellings
27,Semi-detached house,Ward 1,1425,2021,dwellings
28,Row house,Ward 1,3645,2021,dwellings
29,Apartment or flat in a duplex,Ward 1,3790,2021,dwellings
30,Apartment in a building that has fewer than fi...,Ward 1,2015,2021,dwellings
31,Apartment in a building that has five or more ...,Ward 1,15980,2021,dwellings
32,Other single-attached house,Ward 1,10,2021,dwellings
33,Movable dwelling,Ward 1,0,2021,dwellings
34,Total - Tenure (includes band housing),Ward 1,38130,2021,dwellings
35,Owned,Ward 1,20790,2021,dwellings
36,Part of a condominium,Ward 1,6380,2021,dwellings
37,Not part of a condominium,Ward 1,14405,2021,dwellings
38,Rented,Ward 1,17340,2021,dwellings
39,Part of a condominium,Ward 1,2535,2021,dwellings
40,Not part of a condominium,Ward 1,14810,2021,dwellings
41,Total - Occupied private dwellings by period o...,Ward 1,38135,2021,dwellings
42,1960 or before,Ward 1,8360,2021,dwellings
43,1961 to 1980,Ward 1,15990,2021,dwellings
44,1981 to 1990,Ward 1,5760,2021,dwellings
45,1991 to 2000,Ward 1,4445,2021,dwellings
46,2001 to 2005,Ward 1,1055,2021,dwellings
47,2006 to 2010,Ward 1,1175,2021,dwellings
48,2011 to 2015,Ward 1,745,2021,dwellings
49,2016 to 2021,Ward 1,590,2021,dwellings
674,Total - Occupied private dwellings by structur...,Ward 1,37895,2016,dwellings
675,Single-detached house,Ward 1,11225,2016,dwellings
676,Semi-detached house,Ward 1,1360,2016,dwellings
677,Row house,Ward 1,3610,2016,dwellings
678,Apartment or flat in a duplex,Ward 1,3945,2016,dwellings
679,Apartment in a building that has fewer than fi...,Ward 1,2055,2016,dwellings
680,Apartment in a building that has five or more ...,Ward 1,15695,2016,dwellings
681,Other single-attached house,Ward 1,0,2016,dwellings
682,Movable dwelling,Ward 1,0,2016,dwellings
683,Total - Tenure (includes band housing),Ward 1,37895,2016,dwellings
684,Owned,Ward 1,20945,2016,dwellings
685,Part of a condominium,Ward 1,6045,2016,dwellings
686,Not part of a condominium,Ward 1,14900,2016,dwellings
687,Rented,Ward 1,16945,2016,dwellings
688,Part of a condominium,Ward 1,2400,2016,dwellings
689,Not part of a condominium,Ward 1,14550,2016,dwellings
690,Total - Occupied private dwellings by period o...,Ward 1,37890,2016,dwellings
691,1960 or before,Ward 1,8785,2016,dwellings
692,1961 to 1980,Ward 1,16515,2016,dwellings
693,1981 to 1990,Ward 1,6185,2016,dwellings
694,1991 to 2000,Ward 1,3735,2016,dwellings
695,2001 to 2005,Ward 1,845,2016,dwellings
696,2006 to 2010,Ward 1,1160,2016,dwellings
697,2011 to 2016,Ward 1,670,2016,dwellings

In [8]:
#Clean dwellings census data
dwelling = data['dwellings_long']
print(ds.quick_summary(dwelling))
dwelling = dwelling[~dwelling["variable"].str.contains("total", case=False, na=False)] #drop variable containing string "total"
dwelling = dwelling[~dwelling["geography"].str.contains("toronto", case=False, na=False)].reset_index(drop=True) # drop geography = Toronto
dwelling

            dtype  col_index  missing_pct  n_unique
variable   object          0          0.0        24
geography  object          1          0.0        26
value       int64          2          0.0       985
year        int64          3          0.0         2
category   object          4          0.0         1

,variable,geography,value,year,category
0,Single-detached house,Ward 1,11270,2021,dwellings
1,Semi-detached house,Ward 1,1425,2021,dwellings
2,Row house,Ward 1,3645,2021,dwellings
3,Apartment or flat in a duplex,Ward 1,3790,2021,dwellings
4,Apartment in a building that has fewer than fi...,Ward 1,2015,2021,dwellings
...,...,...,...,...,...
1070,1981 to 1990,Ward 25,8940,2016,dwellings
1071,1991 to 2000,Ward 25,5050,2016,dwellings
1072,2001 to 2005,Ward 25,3205,2016,dwellings
1073,2006 to 2010,Ward 25,1665,2016,dwellings
1074,2011 to 2016,Ward 25,480,2016,dwellings

In [9]:
dwelling['variable'].value_counts()

variable
Not part of a condominium                                   100
Part of a condominium                                       100
Semi-detached house                                          50
2006 to 2010                                                 50
2001 to 2005                                                 50
1991 to 2000                                                 50
1981 to 1990                                                 50
1961 to 1980                                                 50
1960 or before                                               50
Rented                                                       50
Single-detached house                                        50
Owned                                                        50
Movable dwelling                                             50
Other single-attached house                                  50
Apartment in a building that has five or more storeys        50
Apartment in a building that has fewer than five storeys     50
Apartment or flat in a duplex                                50
Row house                                                    50
2011 to 2015                                                 25
2016 to 2021                                                 25
2011 to 2016                                                 25
Name: count, dtype: int64

In [10]:
totals = ds.search_df(dwelling, "total", None,"variable")
totals["variable"]

Series([], Name: variable, dtype: object)

In [11]:
dwelling['year'].value_counts()

year
2021    550
2016    525
Name: count, dtype: int64

### Mapping and transform

In [12]:
import pandas as pd


def transform_dwellings_reduced(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    # Clean string columns just in case
    df["variable"] = df["variable"].astype(str).str.strip()

    # ----------------------------
    # 1. Exhaustive mappings
    # ----------------------------
    type_map = {
        "Single-detached house": "detached",
        "Semi-detached house": "attached/other",
        "Row house": "attached/other",
        "Other single-attached house": "attached/other",
        "Apartment or flat in a duplex": "apartment",
        "Apartment in a building that has fewer than five storeys": "apartment",
        "Apartment in a building that has five or more storeys": "apartment",
        "Movable dwelling": "attached/other"   # very negligible, fold into attached instead of other
    }

    condo_map = {
        "Part of a condominium": "condo",
        "Not part of a condominium": "non_condo",
    }

    ownership_map = {
        "Owned": "owned",
        "Rented": "rented",
    }

    age_map = {
        "1960 or before": "pre_1980",
        "1961 to 1980": "pre_1980",
    
        "1981 to 1990": "1980_2000",
        "1991 to 2000": "1980_2000",
    
        "2001 to 2005": "2000_2010",
        "2006 to 2010": "2000_2010",
    
        "2011 to 2015": "2010_2020",
        "2011 to 2016": "2010_2020",  # dataset variant
        "2016 to 2021": "2010_2020",
    
        # future-proof (in case newer data appears)
        "2021 to 2026": "post_2020",
        "2022 to 2026": "post_2020",
    }

    # ----------------------------
    # 2. Assign reduced groups
    # ----------------------------
    df["type_group"] = df["variable"].map(type_map)
    df["condo_group"] = df["variable"].map(condo_map)
    df["ownership_group"] = df["variable"].map(ownership_map)
    df["age_group"] = df["variable"].map(age_map)

    # ----------------------------
    # 3. Validate coverage
    # ----------------------------
    covered = (
        df["type_group"].notna()
        | df["condo_group"].notna()
        | df["ownership_group"].notna()
        | df["age_group"].notna()
    )

    unmapped = sorted(df.loc[~covered, "variable"].dropna().unique())
    if unmapped:
        raise ValueError(f"Unmapped dwelling variables found: {unmapped}")

    # ----------------------------
    # 4. Helper to compute subgroup %
    # ----------------------------
    def compute_pct(subset: pd.DataFrame, group_col: str) -> pd.DataFrame:
        grouped = (
            subset.groupby(["geography", "year", group_col], as_index=False)["value"]
            .sum()
        )

        grouped["denominator"] = grouped.groupby(["geography", "year"])["value"].transform("sum")
        grouped["pct"] = grouped["value"] / grouped["denominator"]

        wide = (
            grouped.pivot(index=["geography", "year"], columns=group_col, values="pct")
            .reset_index()
        )
        wide.columns.name = None
        return wide

    # ----------------------------
    # 5. Build reduced blocks
    # ----------------------------
    type_df = compute_pct(df[df["type_group"].notna()], "type_group")
    condo_df = compute_pct(df[df["condo_group"].notna()], "condo_group")
    ownership_df = compute_pct(df[df["ownership_group"].notna()], "ownership_group")
    age_df = compute_pct(df[df["age_group"].notna()], "age_group")

    # ----------------------------
    # 6. Merge blocks
    # ----------------------------
    final = type_df.merge(condo_df, on=["geography", "year"], how="outer")
    final = final.merge(ownership_df, on=["geography", "year"], how="outer")
    final = final.merge(age_df, on=["geography", "year"], how="outer")

    # ----------------------------
    # 7. Rename final columns
    # ----------------------------
    final = final.rename(columns={
        "detached": "pct_detached",
        "attached/other": "pct_attached/other",
        "apartment": "pct_apartment",
        "condo": "pct_condo",
        "non_condo": "pct_non_condo",
        "owned": "pct_owned",
        "rented": "pct_rented",
        "pre_1980": "pct_pre_1980",
        "1980_2000": "pct_1980_2000",
        "2000_2010": "pct_2000_2010",
        "2010_2020": "pct_2010_2020",
        "post_2020": "pct_post_2020",
    })

    # Optional: keep only the most useful reduced features
    keep_cols = [
        "geography",
        "year",
        "pct_detached",
        "pct_attached/other",
        "pct_apartment",
        "pct_condo",
        "pct_non_condo",
        "pct_pre_1980",
        "pct_1980_2000",
        "pct_2000_2010",
        "pct_2010_2020",
        "pct_post_2020",
    ]
    existing_cols = [c for c in keep_cols if c in final.columns]
    final = final[existing_cols]

    return final

In [13]:
dwellings_trans = transform_dwellings_reduced(dwelling)
dwellings_trans

,geography,year,pct_detached,pct_attached/other,pct_apartment,pct_condo,pct_non_condo,pct_pre_1980,pct_1980_2000,pct_2000_2010,pct_2010_2020
0,Ward 1,2016,0.296252,0.131169,0.572579,0.222853,0.777147,0.667634,0.261776,0.052909,0.017680
1,Ward 1,2021,0.295529,0.133211,0.571260,0.233805,0.766195,0.638772,0.267707,0.058499,0.035021
2,Ward 10,2016,0.007581,0.049315,0.943103,0.793405,0.206595,0.163085,0.172873,0.347733,0.316309
3,Ward 10,2021,0.006193,0.041246,0.952561,0.833148,0.166852,0.132541,0.146166,0.271832,0.449461
4,Ward 11,2016,0.082699,0.118239,0.799063,0.311432,0.688568,0.650625,0.147794,0.111187,0.090394
5,Ward 11,2021,0.078124,0.116157,0.805719,0.382020,0.617980,0.573031,0.139893,0.107653,0.179422
6,Ward 12,2016,0.166729,0.072540,0.760731,0.186018,0.813982,0.721327,0.147770,0.093047,0.037856
7,Ward 12,2021,0.152284,0.064441,0.783275,0.274847,0.725153,0.616384,0.139059,0.080802,0.163755
8,Ward 13,2016,0.004016,0.051102,0.944881,0.424763,0.575237,0.464536,0.233123,0.170227,0.132114
9,Ward 13,2021,0.003625,0.045824,0.950551,0.528132,0.471868,0.366154,0.197578,0.132323,0.303944
10,Ward 14,2016,0.182340,0.268039,0.549621,0.074973,0.925027,0.831509,0.090151,0.040416,0.037924
11,Ward 14,2021,0.181917,0.272875,0.545209,0.098962,0.901038,0.789314,0.093230,0.046182,0.071274
12,Ward 15,2016,0.371677,0.102180,0.526143,0.123110,0.876890,0.705467,0.154195,0.096372,0.043966
13,Ward 15,2021,0.367974,0.100674,0.531351,0.148407,0.851593,0.649138,0.162378,0.092556,0.095928
14,Ward 16,2016,0.145185,0.134673,0.720142,0.293407,0.706593,0.709182,0.188756,0.078418,0.023644
15,Ward 16,2021,0.141700,0.130077,0.728223,0.313830,0.686170,0.675637,0.187590,0.078903,0.057871
16,Ward 17,2016,0.209015,0.185477,0.605508,0.365819,0.634181,0.658034,0.126310,0.100177,0.115480
17,Ward 17,2021,0.192791,0.169088,0.638121,0.424312,0.575688,0.573285,0.132481,0.096439,0.197794
18,Ward 18,2016,0.245221,0.052848,0.701932,0.546483,0.453517,0.330264,0.240793,0.306946,0.121998
19,Ward 18,2021,0.245772,0.052715,0.701513,0.547028,0.452972,0.308704,0.243027,0.283877,0.164392
20,Ward 19,2016,0.278665,0.185632,0.535703,0.090781,0.909219,0.826829,0.103816,0.050114,0.019241
21,Ward 19,2021,0.279899,0.184922,0.535179,0.112351,0.887649,0.788011,0.110698,0.049552,0.051739
22,Ward 2,2016,0.483849,0.063270,0.452880,0.201354,0.798646,0.810010,0.103207,0.042948,0.043835
23,Ward 2,2021,0.482188,0.064079,0.453733,0.214112,0.785888,0.776883,0.106320,0.042682,0.074115
24,Ward 20,2016,0.356024,0.117711,0.526265,0.104591,0.895409,0.748072,0.152048,0.068554,0.031325
25,Ward 20,2021,0.354458,0.123523,0.522019,0.118602,0.881398,0.697530,0.160124,0.072426,0.069920
26,Ward 21,2016,0.344999,0.087118,0.567883,0.240288,0.759712,0.717637,0.146829,0.097679,0.037855
27,Ward 21,2021,0.342251,0.090494,0.567254,0.252773,0.747227,0.684872,0.159413,0.093946,0.061768
28,Ward 22,2016,0.303591,0.156148,0.540261,0.354461,0.645539,0.606992,0.281866,0.058495,0.052646
29,Ward 22,2021,0.288863,0.155060,0.556077,0.374625,0.625375,0.567405,0.277184,0.061538,0.093872
30,Ward 23,2016,0.402011,0.253920,0.344070,0.274106,0.725894,0.445050,0.409780,0.127790,0.017379
31,Ward 23,2021,0.399187,0.251566,0.349247,0.275004,0.724996,0.441868,0.389744,0.125571,0.042816
32,Ward 24,2016,0.340292,0.080863,0.578845,0.205064,0.794936,0.722099,0.192736,0.070693,0.014473
33,Ward 24,2021,0.337288,0.081942,0.580770,0.220306,0.779694,0.682345,0.206897,0.072966,0.037793
34,Ward 25,2016,0.547545,0.203472,0.248983,0.141718,0.858282,0.394869,0.437735,0.152378,0.015019
35,Ward 25,2021,0.547269,0.204240,0.248491,0.146349,0.853651,0.388519,0.419774,0.144979,0.046728
36,Ward 3,2016,0.305742,0.061684,0.632574,0.316283,0.683717,0.575375,0.142546,0.155353,0.126726
37,Ward 3,2021,0.283438,0.057038,0.659524,0.380509,0.619491,0.501182,0.139404,0.139099,0.220316
38,Ward 4,2016,0.175676,0.109102,0.715223,0.135546,0.864454,0.819654,0.083665,0.048291,0.048390
39,Ward 4,2021,0.179088,0.110729,0.710183,0.150268,0.849732,0.790959,0.088896,0.048544,0.071602
40,Ward 5,2016,0.293044,0.099833,0.607123,0.115847,0.884153,0.727212,0.188314,0.073678,0.010796
41,Ward 5,2021,0.292753,0.102430,0.604816,0.122503,0.877497,0.698513,0.199401,0.067022,0.035064
42,Ward 6,2016,0.255522,0.103665,0.640813,0.206451,0.793549,0.680472,0.185241,0.071285,0.063002
43,Ward 6,2021,0.250757,0.104785,0.644458,0.236064,0.763936,0.609449,0.192974,0.078740,0.118837
44,Ward 7,2016,0.126588,0.315848,0.557565,0.145678,0.854322,0.762878,0.149151,0.062422,0.025549
45,Ward 7,2021,0.124502,0.308866,0.566631,0.163217,0.836783,0.702932,0.167441,0.065941,0.063686
46,Ward 8,2016,0.388399,0.062189,0.549412,0.148931,0.851069,0.711428,0.155759,0.087826,0.044987
47,Ward 8,2021,0.374428,0.067632,0.557939,0.189460,0.810540,0.642818,0.162256,0.081999,0.112926
48,Ward 9,2016,0.143562,0.202128,0.654310,0.122847,0.877153,0.760035,0.090590,0.065475,0.083900
49,Ward 9,2021,0.141653,0.208867,0.649480,0.149458,0.850542,0.706732,0.102901,0.067652,0.122715

In [14]:
def validate_dwellings_output(
    df: pd.DataFrame,
    tol: float = 1e-3,
    verbose: bool = True
) -> dict:
    """
    Validate that percentage groups sum to ~1.

    Returns dict with summary + problematic rows.
    """

    results = {}

    groups = {
        "type": ["pct_detached", "pct_attached/other", "pct_apartment"],
        "age": [
            "pct_pre_1980",
            "pct_1980_2000",
            "pct_2000_2010",
            "pct_2010_2020",
            "pct_post_2020",
        ],
        "condo": ["pct_condo", "pct_non_condo"],
    }

    for group_name, cols in groups.items():
        existing_cols = [c for c in cols if c in df.columns]

        if not existing_cols:
            continue

        df[f"{group_name}_sum"] = df[existing_cols].sum(axis=1)

        bad_mask = ~df[f"{group_name}_sum"].between(1 - tol, 1 + tol)

        results[group_name] = {
            "columns": existing_cols,
            "mean_sum": df[f"{group_name}_sum"].mean(),
            "min_sum": df[f"{group_name}_sum"].min(),
            "max_sum": df[f"{group_name}_sum"].max(),
            "bad_rows_count": bad_mask.sum(),
            "bad_rows": df.loc[bad_mask, ["geography", "year", f"{group_name}_sum"]],
        }

        if verbose:
            print(f"\n--- {group_name.upper()} CHECK ---")
            print(f"Columns: {existing_cols}")
            print(f"Mean: {results[group_name]['mean_sum']:.6f}")
            print(f"Min:  {results[group_name]['min_sum']:.6f}")
            print(f"Max:  {results[group_name]['max_sum']:.6f}")
            print(f"Bad rows: {results[group_name]['bad_rows_count']}")

    return results

In [15]:
dwellings_trans.columns

Index(['geography', 'year', 'pct_detached', 'pct_attached/other',
       'pct_apartment', 'pct_condo', 'pct_non_condo', 'pct_pre_1980',
       'pct_1980_2000', 'pct_2000_2010', 'pct_2010_2020'],
      dtype='object')

## Education Transformation 2/8

Hierarchy looks as thus: 
Total - Highest certificate, diploma or degree
│
├── No certificate, diploma or degree
│
├── High (secondary) school diploma or equivalency certificate
│
└── Postsecondary certificate, diploma or degree
    │
    ├── Postsecondary certificate or diploma below bachelor level
    │   │
    │   ├── Apprenticeship or trades certificate or diploma
    │   │   ├── Apprenticeship certificate
    │   │   └── Non-apprenticeship trades certificate or diploma
    │   │
    │   ├── College, CEGEP or other non-university certificate or diploma
    │   │
    │   └── University certificate or diploma below bachelor level
    │
    └── Bachelor's degree or higher
        │
        ├── Bachelor's degree
        │
        ├── University certificate or diploma above bachelor level
        │
        ├── Degree in medicine, dentistry, veterinary medicine or optometry
        │
        ├── Master's degree
        │
        └── Earned doctorate

In [120]:
# ----------------------------
# EDUCATION MAPPING (AI-READY)
# ----------------------------
# Goal:
# Convert detailed census education categories into a flat, mutually exclusive
# distribution that sums to 1 and represents an ordinal education gradient.
#
# IMPORTANT RULES:
# - Only use LEAF categories (no aggregates)
# - Do NOT include totals or rollups (they cause double counting)
# - All groups must be mutually exclusive
# - Groups should represent increasing education level (ordinal structure)
#
# Final interpretation for models:
# pct_no_highschool         → lowest attainment
# pct_highschool            → basic attainment
# pct_postsecondary_non_uni → trades / college
# pct_university_plus       → highest attainment
#
# These features:
# - sum to ~1 within each geography/year
# - encode a monotonic socioeconomic gradient
# - are safe for aggregation and modeling

edu_map = {
    # --- Lowest education ---
    "No certificate, diploma or degree": "no_highschool",

    # --- High school ---
    "High (secondary) school diploma or equivalency certificate": "highschool",
    "Secondary (high) school diploma or equivalency certificate": "highschool",

    # --- Postsecondary (NON-university) ---
    # NOTE: only include leaf categories, NOT aggregates like:
    # "Postsecondary certificate, diploma or degree"
    # "Postsecondary certificate or diploma below bachelor level"
    # "Apprenticeship or trades certificate or diploma"
    "Apprenticeship certificate": "postsecondary_non_uni",
    "Non-apprenticeship trades certificate or diploma": "postsecondary_non_uni",
    "Trades certificate or diploma other than Certificate of Apprenticeship or Certificate of Qualification": "postsecondary_non_uni",
    "Certificate of Apprenticeship or Certificate of Qualification": "postsecondary_non_uni",
    "College, CEGEP or other non-university certificate or diploma": "postsecondary_non_uni",
    "University certificate or diploma below bachelor level": "postsecondary_non_uni",

    # --- University and above ---
    # NOTE: exclude aggregate rows like:
    # "Bachelor’s degree or higher"
    # "University certificate, diploma or degree at bachelor level or above"
    "Bachelor's degree": "university_plus",
    "University certificate or diploma above bachelor level": "university_plus",
    "Master's degree": "university_plus",
    "Earned doctorate": "university_plus",
    "Degree in medicine, dentistry, veterinary medicine or optometry": "university_plus",
}

In [109]:
edu = data['education_long']
edu[edu['geography']=='Ward 1']

,variable,geography,value,year,category
16,"Total - Highest certificate, diploma or degree...",Ward 1,96620,2021,education
17,"No certificate, diploma or degree",Ward 1,21870,2021,education
18,High (secondary) school diploma or equivalency...,Ward 1,28780,2021,education
19,"Postsecondary certificate, diploma or degree",Ward 1,45965,2021,education
20,Postsecondary certificate or diploma below bac...,Ward 1,23845,2021,education
21,Apprenticeship or trades certificate or diploma,Ward 1,4400,2021,education
22,Non-apprenticeship trades certificate or diploma,Ward 1,2580,2021,education
23,Apprenticeship certificate,Ward 1,1820,2021,education
24,"College, CEGEP or other non-university certifi...",Ward 1,16295,2021,education
25,University certificate or diploma below bachel...,Ward 1,3145,2021,education
26,Bachelor’s degree or higher,Ward 1,22120,2021,education
27,Bachelor's degree,Ward 1,15115,2021,education
28,University certificate or diploma above bachel...,Ward 1,1670,2021,education
29,"Degree in medicine, dentistry, veterinary medi...",Ward 1,385,2021,education
30,Master's degree,Ward 1,4560,2021,education
31,Earned doctorate,Ward 1,400,2021,education
431,"Total - Highest certificate, diploma or degree...",Ward 1,95295,2016,education
432,"No certificate, diploma or degree",Ward 1,23735,2016,education
433,Secondary (high) school diploma or equivalency...,Ward 1,29205,2016,education
434,"Postsecondary certificate, diploma or degree",Ward 1,42350,2016,education
435,Apprenticeship or trades certificate or diploma,Ward 1,5205,2016,education
436,Trades certificate or diploma other than Certi...,Ward 1,2850,2016,education
437,Certificate of Apprenticeship or Certificate o...,Ward 1,2355,2016,education
438,"College, CEGEP or other non-university certifi...",Ward 1,16140,2016,education
439,University certificate or diploma below bachel...,Ward 1,2560,2016,education
440,"University certificate, diploma or degree at b...",Ward 1,18445,2016,education
441,Bachelor's degree,Ward 1,12800,2016,education
442,University certificate or diploma above bachel...,Ward 1,1210,2016,education
443,"Degree in medicine, dentistry, veterinary medi...",Ward 1,455,2016,education
444,Master's degree,Ward 1,3645,2016,education
445,Earned doctorate,Ward 1,330,2016,education

In [16]:
#Clean dwellings census data
edu = data['education_long']
print(ds.quick_summary(edu))
edu = edu[~edu["variable"].str.contains("total", case=False, na=False)] #drop variable containing string "total"
edu = edu[~edu["geography"].str.contains("toronto", case=False, na=False)].reset_index(drop=True) # drop geography = Toronto
edu

            dtype  col_index  missing_pct  n_unique
variable   object          0          0.0        20
geography  object          1          0.0        26
value       int64          2          0.0       717
year        int64          3          0.0         2
category   object          4          0.0         1

,variable,geography,value,year,category
0,"No certificate, diploma or degree",Ward 1,21870,2021,education
1,High (secondary) school diploma or equivalency...,Ward 1,28780,2021,education
2,"Postsecondary certificate, diploma or degree",Ward 1,45965,2021,education
3,Postsecondary certificate or diploma below bac...,Ward 1,23845,2021,education
4,Apprenticeship or trades certificate or diploma,Ward 1,4400,2021,education
...,...,...,...,...,...
720,Bachelor's degree,Ward 25,15120,2016,education
721,University certificate or diploma above bachel...,Ward 25,1280,2016,education
722,"Degree in medicine, dentistry, veterinary medi...",Ward 25,420,2016,education
723,Master's degree,Ward 25,3670,2016,education
724,Earned doctorate,Ward 25,335,2016,education

In [17]:
edu['variable'].value_counts() #we will drop aggregates and keep leaf variables, re-aggregate manually after

variable
No certificate, diploma or degree                                                                         50
Master's degree                                                                                           50
Postsecondary certificate, diploma or degree                                                              50
Apprenticeship or trades certificate or diploma                                                           50
College, CEGEP or other non-university certificate or diploma                                             50
University certificate or diploma below bachelor level                                                    50
Earned doctorate                                                                                          50
Bachelor's degree                                                                                         50
University certificate or diploma above bachelor level                                                    50
Degree in medicine, dentistry, veterinary medicine or optometry                                           50
Certificate of Apprenticeship or Certificate of Qualification                                             25
Trades certificate or diploma other than Certificate of Apprenticeship or Certificate of Qualification    25
Secondary (high) school diploma or equivalency certificate                                                25
Bachelor’s degree or higher                                                                               25
High (secondary) school diploma or equivalency certificate                                                25
Apprenticeship certificate                                                                                25
Non-apprenticeship trades certificate or diploma                                                          25
Postsecondary certificate or diploma below bachelor level                                                 25
University certificate, diploma or degree at bachelor level or above                                      25
Name: count, dtype: int64

In [111]:
edu_leaf = edu[
    ~edu["variable"].str.contains("Postsecondary certificate, diploma or degree", case=False, na=False)
]

edu_leaf = edu_leaf[
    ~edu_leaf["variable"].str.contains("Bachelor’s degree or higher", case=False, na=False)
]

edu_leaf = edu_leaf[
    ~edu_leaf["variable"].str.contains("bachelor level or above", case=False, na=False)
].reset_index(drop=True)
edu_leaf

,variable,geography,value,year,category
0,"Total - Highest certificate, diploma or degree...",Toronto,2377950,2021,education
1,"No certificate, diploma or degree",Toronto,339500,2021,education
2,High (secondary) school diploma or equivalency...,Toronto,555590,2021,education
3,Postsecondary certificate or diploma below bac...,Toronto,506235,2021,education
4,Apprenticeship or trades certificate or diploma,Toronto,80930,2021,education
...,...,...,...,...,...
697,Bachelor's degree,Ward 25,15120,2016,education
698,University certificate or diploma above bachel...,Ward 25,1280,2016,education
699,"Degree in medicine, dentistry, veterinary medi...",Ward 25,420,2016,education
700,Master's degree,Ward 25,3670,2016,education
701,Earned doctorate,Ward 25,335,2016,education

In [19]:
edu_leaf['variable'].value_counts()

variable
No certificate, diploma or degree                                                                         50
University certificate or diploma below bachelor level                                                    50
Earned doctorate                                                                                          50
Master's degree                                                                                           50
Degree in medicine, dentistry, veterinary medicine or optometry                                           50
University certificate or diploma above bachelor level                                                    50
Bachelor's degree                                                                                         50
College, CEGEP or other non-university certificate or diploma                                             50
Apprenticeship or trades certificate or diploma                                                           50
Bachelor’s degree or higher                                                                               25
High (secondary) school diploma or equivalency certificate                                                25
Apprenticeship certificate                                                                                25
Non-apprenticeship trades certificate or diploma                                                          25
Postsecondary certificate or diploma below bachelor level                                                 25
Secondary (high) school diploma or equivalency certificate                                                25
Trades certificate or diploma other than Certificate of Apprenticeship or Certificate of Qualification    25
Certificate of Apprenticeship or Certificate of Qualification                                             25
University certificate, diploma or degree at bachelor level or above                                      25
Name: count, dtype: int64

### Mapping and transform

In [118]:
def transform_education(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["variable"] = df["variable"].astype(str).str.strip()

    # mapping
    edu_map = {
        "No certificate, diploma or degree": "no_highschool",
        "High (secondary) school diploma or equivalency certificate": "highschool",
        "Secondary (high) school diploma or equivalency certificate": "highschool",

        #"Apprenticeship or trades certificate or diploma": "postsecondary_non_uni",
        "Apprenticeship certificate": "postsecondary_non_uni",
        "Non-apprenticeship trades certificate or diploma": "postsecondary_non_uni",
        "Trades certificate or diploma other than Certificate of Apprenticeship or Certificate of Qualification": "postsecondary_non_uni",
        "Certificate of Apprenticeship or Certificate of Qualification": "postsecondary_non_uni",
        "College, CEGEP or other non-university certificate or diploma": "postsecondary_non_uni",
        "University certificate or diploma below bachelor level": "postsecondary_non_uni",
        #"Postsecondary certificate or diploma below bachelor level": "postsecondary_non_uni",

        "Bachelor's degree": "university_plus",
        "University certificate or diploma above bachelor level": "university_plus",
        #"University certificate, diploma or degree at bachelor level or above": "university_plus",
        "Master's degree": "university_plus",
        "Earned doctorate": "university_plus",
        "Degree in medicine, dentistry, veterinary medicine or optometry": "university_plus",
    }

    # map groups
    df["edu_group"] = df["variable"].map(edu_map)

    # filter valid rows only (drops aggregates like "Postsecondary certificate, diploma or degree")
    df = df[df["edu_group"].notna()].copy()

    # aggregate
    grouped = (
        df.groupby(["geography", "year", "edu_group"], as_index=False)["value"]
        .sum()
    )

    # compute %
    grouped["total"] = grouped.groupby(["geography", "year"])["value"].transform("sum")
    grouped["pct"] = grouped["value"] / grouped["total"]

    # pivot wide
    wide = (
        grouped.pivot(index=["geography", "year"], columns="edu_group", values="pct")
        .reset_index()
    )

    wide.columns.name = None

    # rename final columns
    wide = wide.rename(columns={
        "no_highschool": "pct_no_highschool",
        "highschool": "pct_highschool",
        "postsecondary_non_uni": "pct_postsecondary_non_uni",
        "university_plus": "pct_university_plus",
    })

    return wide

In [119]:
max_edu = transform_education(edu_leaf)
max_edu[max_edu['geography'] == 'Ward 1']

,geography,year,pct_highschool,pct_no_highschool,pct_postsecondary_non_uni,pct_university_plus
2,Ward 1,2016,0.306502,0.249095,0.250879,0.193525
3,Ward 1,2021,0.297868,0.226351,0.246740,0.229042

## Ethnic Transformation 3/8
ethnic_long

In [125]:
ethnic = data['ethnic_long']
ethnic [ ethnic['geography']=='Ward 1']

,variable,geography,value,year,category
266,Total - Ethnic or cultural origin for the popu...,Ward 1,115115,2021,ethnic
267,Canadian,Ward 1,6335,2021,ethnic
268,English,Ward 1,3330,2021,ethnic
269,Irish,Ward 1,2945,2021,ethnic
270,Scottish,Ward 1,2640,2021,ethnic
...,...,...,...,...,...
7499,Korean,Ward 1,480,2016,ethnic
7500,Japanese,Ward 1,145,2016,ethnic
7501,"Visible minority, n.i.e.",Ward 1,4115,2016,ethnic
7502,Multiple visible minorities,Ward 1,2355,2016,ethnic
7503,Not a visible minority,Ward 1,28460,2016,ethnic

In [127]:
ethnic.variable.unique()

array(['Total - Ethnic or cultural origin for the population in private households - 25% sample data',
       'Canadian', 'English', 'Irish', 'Scottish', 'French, n.o.s.',
       'German', 'Chinese', 'Italian', 'Indian (India)', 'Ukrainian',
       'Dutch', 'Polish', 'Québécois', 'British Isles, n.o.s.',
       'Filipino', 'French Canadian', 'Caucasian (White), n.o.s.',
       'First Nations (North American Indian), n.o.s.', 'Métis',
       'European, n.o.s.', 'Russian', 'Norwegian', 'Welsh', 'Portuguese',
       'American', 'Spanish', 'Swedish', 'Hungarian', 'Acadian',
       'Pakistani', 'African, n.o.s.', 'Jewish', 'Punjabi', 'Vietnamese',
       'Arab, n.o.s.', 'Greek', 'Jamaican', 'Asian, n.o.s.',
       'Cree, n.o.s.', 'Korean', 'Romanian', 'Lebanese', 'Iranian',
       'Christian, n.i.e.', 'Danish', 'North American Indigenous, n.o.s.',
       'Sikh', 'Austrian', 'Belgian', 'Haitian', 'Hindu', 'Mexican',
       'Mennonite', 'Swiss', 'Finnish', 'Sri Lankan', 'Croatian',
       'Japanese', 'South Asian, n.o.s.', "Mi'kmaq, n.o.s.",
       'Northern European, n.o.s.', 'Muslim', 'Egyptian',
       'Latin, Central or South American, n.o.s.', 'Tamil', 'Icelandic',
       'Colombian', 'Moroccan', 'Czech', 'Syrian', 'Guyanese', 'Afghan',
       'Black, n.o.s.', 'Serbian', 'Ojibway', 'Newfoundlander',
       'Hong Konger', 'Ontarian', 'Persian', 'Trinidadian/Tobagonian',
       'Turkish', 'Inuit, n.o.s.', 'Bangladeshi', 'Algerian', 'Brazilian',
       'Nigerian', 'Armenian', 'Slovak', 'Eastern European, n.o.s.',
       'Somali', 'Taiwanese', 'Iraqi', 'Salvadorean', 'African Caribbean',
       'East or Southeast Asian, n.o.s.',
       'West or Central Asian or Middle Eastern, n.o.s.',
       'Caribbean, n.o.s.', 'Algonquin', 'West Indian, n.o.s.',
       'Lithuanian', 'South African', 'Australian', 'Palestinian',
       'Chilean', 'Congolese', 'Nova Scotian', 'Ethiopian',
       'Hispanic, n.o.s.', 'Peruvian', 'Yoruba', 'Cambodian (Khmer)',
       'Berber', 'Albanian', 'Maltese', 'Macedonian', 'Slovenian',
       'Western European, n.o.s.', 'New Brunswicker', 'Gujarati',
       'Eritrean', 'African Canadian', 'Israeli', 'Mohawk',
       'Czechoslovakian, n.o.s.', 'Bulgarian', 'Albertan', 'Ghanaian',
       'Barbadian', 'African American', 'Yugoslavian, n.o.s.', 'Tunisian',
       'Slavic, n.o.s.', 'Cuban', 'Bosnian', 'Venezuelan',
       'Innu/Montagnais, n.o.s.', 'Latvian', 'Bengali', 'Cameroonian',
       'Guatemalan', 'Indonesian', 'Laotian', 'Ilocano', 'Northern Irish',
       'Celtic, n.o.s.', 'British Columbian', 'Ecuadorian',
       'Franco Ontarian', 'Argentinian', 'Estonian', 'Kurdish', 'Fijian',
       'Jatt', 'North American, n.o.s.', 'Coptic', 'Thai', 'Dominican',
       'Nepali', 'Kabyle', 'Assyrian', 'Igbo', 'Byelorussian',
       'Dene, n.o.s.', 'Blackfoot, n.o.s.', 'Abenaki', 'Moldovan',
       'Iroquois (Haudenosaunee), n.o.s.', 'New Zealander', 'Sudanese',
       'Breton', 'Pennsylvania Dutch', 'Malaysian', 'Plains Cree',
       'North African, n.o.s.', 'Huron (Wendat)', 'Saskatchewanian',
       'Buddhist', 'Gaspesian', 'Norman',
       'Southern or East African, n.o.s.', 'Ivorian', 'Saulteaux',
       'Anishinaabe, n.o.s.', 'Burundian', 'Tigrinya', 'Nicaraguan',
       'Mauritian', 'Kenyan', 'Oji-Cree', 'Vincentian', 'Jordanian',
       'Manitoban', 'Cape Bretoner', 'Rwandan', 'Grenadian', 'Malayali',
       'Chaldean', 'Sinhalese', 'Mayan', 'Honduran', 'Cherokee',
       "Qalipu Mi'kmaq", 'Indo-Caribbean', 'Flemish',
       'United Empire Loyalist', 'Senegalese', 'Azerbaijani', 'Sicilian',
       'Pashtun', 'Malay', 'Goan', 'Bantu, n.o.s.', 'Tibetan',
       'Zimbabwean', 'Burmese', 'Mongolian', 'Azorean', 'Atikamekw',
       'Bamileke', 'Indo-Guyanese', 'Ugandan', 'Oromo', 'Tanzanian',
       'Yemeni', 'Central African', 'Libyan', 'Basque', 'Uruguayan',
       'Akan, n.o.s.', 'Central or West African, n.o.s.', 'Igorot',
       'Fulani', 'Woodland Cree', 'Guinean', 'St. Lucian',
       'Prince Edward Islander', 'Maliseet', 'Beninese', 'Telugu', 'Roma',
       'Costa Rican', 'African Nova Scotian', 'Malagasy', 'Kashmiri',
       'Singaporean', 'Karen', 'Edo', 'Tajik', 'Amhara', 'Paraguayan',
       'Total - Visible minority for the population in private households - 25% sample data',
       'Total visible minority population', 'South Asian', 'Black',
       'Latin American', 'Arab', 'Southeast Asian', 'West Asian',
       'Visible minority, n.i.e.', 'Multiple visible minorities',
       'Not a visible minority',
       'Total - Ethnic origin for the population in private households - 25% sample data',
       'North American Aboriginal origins',
       'First Nations (North American Indian)', 'Inuit',
       'Other North American origins',
       'Other North American origins, n.i.e.', 'European origins',
       'British Isles origins', 'Channel Islander', 'Cornish', 'Manx',
       'British Isles origins, n.i.e.', 'French origins', 'Alsatian',
       'Corsican', 'French',
       'Western European origins (except French origins)', 'Bavarian',
       'Frisian', 'Luxembourger', 'Western European origins, n.i.e.',
       'Northern European origins (except British Isles origins)',
       'Northern European origins, n.i.e.', 'Eastern European origins',
       'Eastern European origins, n.i.e.', 'Southern European origins',
       'Catalan', 'Cypriot', 'Kosovar', 'Montenegrin',
       'Southern European origins, n.i.e.', 'Other European origins',
       'Roma (Gypsy)', 'Other European origins, n.i.e.',
       'Caribbean origins', 'Antiguan', 'Bahamian', 'Bermudan', 'Carib',
       'Guadeloupean', 'Kittitian/Nevisian', 'Martinican', 'Montserratan',
       'Puerto Rican', 'Vincentian/Grenadinian',
       'Caribbean origins, n.i.e.',
       'Latin, Central and South American origins',
       'Aboriginal from Central/South America (except Arawak and Maya)',
       'Arawak', 'Belizean', 'Bolivian', 'Hispanic', 'Maya', 'Panamanian',
       'Latin, Central and South American origins, n.i.e.',
       'African origins', 'Central and West African origins', 'Akan',
       'Angolan', 'Ashanti', 'Burkinabe', 'Chadian', 'Ewe', 'Gabonese',
       'Gambian', 'Ibo', 'Liberian', 'Malian', 'Malinké', 'Peulh',
       'Sierra Leonean', 'Togolese', 'Wolof',
       'Central and West African origins, n.i.e.',
       'North African origins', 'Dinka', 'Maure',
       'North African origins, n.i.e.',
       'Southern and East African origins', 'Afrikaner', 'Djiboutian',
       'Harari', 'Seychellois', 'Tigrian', 'Zambian', 'Zulu',
       'Southern and East African origins, n.i.e.',
       'Other African origins', 'Other African origins, n.i.e.',
       'Asian origins', 'West Central Asian and Middle Eastern origins',
       'Georgian', 'Hazara', 'Kazakh', 'Kurd', 'Kuwaiti', 'Kyrgyz',
       'Saudi Arabian', 'Tatar', 'Turk', 'Turkmen', 'Uighur', 'Uzbek',
       'West Central Asian and Middle Eastern origins, n.i.e.',
       'South Asian origins', 'Bhutanese', 'East Indian',
       'South Asian origins, n.i.e.', 'East and Southeast Asian origins',
       'Hmong', 'East and Southeast Asian origins, n.i.e.',
       'Other Asian origins', 'Other Asian origins, n.i.e.',
       'Oceania origins', 'Pacific Islands origins', 'Hawaiian', 'Maori',
       'Samoan', 'Polynesian, n.o.s.', 'Pacific Islands origins, n.i.e.'],
      dtype=object)

In [128]:
ethnic = data['ethnic_long']
print(ds.quick_summary(ethnic))
ethnic = ethnic[~ethnic["variable"].str.contains("total", case=False, na=False)]
ethnic = ethnic[~ethnic["geography"].str.contains("toronto", case=False, na=False)]

ethnic = ethnic[
    ~ethnic["variable"].str.contains(
        r"visible minority|multiple visible minorities|origins|n\.o\.s\.|n\.i\.e\.",
        case=False,
        na=False,
        regex=True
    )
].reset_index(drop=True)

            dtype  col_index  missing_pct  n_unique
variable   object          0          0.0       382
geography  object          1          0.0        26
value       int64          2          0.0      1926
year        int64          3          0.0         2
category   object          4          0.0         1

In [24]:
ethnic['variable'].unique()

array(['Canadian', 'English', 'Irish', 'Scottish', 'French, n.o.s.',
       'German', 'Chinese', 'Italian', 'Indian (India)', 'Ukrainian',
       'Dutch', 'Polish', 'Québécois', 'British Isles, n.o.s.',
       'Filipino', 'French Canadian', 'Caucasian (White), n.o.s.',
       'First Nations (North American Indian), n.o.s.', 'Métis',
       'European, n.o.s.', 'Russian', 'Norwegian', 'Welsh', 'Portuguese',
       'American', 'Spanish', 'Swedish', 'Hungarian', 'Acadian',
       'Pakistani', 'African, n.o.s.', 'Jewish', 'Punjabi', 'Vietnamese',
       'Arab, n.o.s.', 'Greek', 'Jamaican', 'Asian, n.o.s.',
       'Cree, n.o.s.', 'Korean', 'Romanian', 'Lebanese', 'Iranian',
       'Christian, n.i.e.', 'Danish', 'North American Indigenous, n.o.s.',
       'Sikh', 'Austrian', 'Belgian', 'Haitian', 'Hindu', 'Mexican',
       'Mennonite', 'Swiss', 'Finnish', 'Sri Lankan', 'Croatian',
       'Japanese', 'South Asian, n.o.s.', "Mi'kmaq, n.o.s.",
       'Northern European, n.o.s.', 'Muslim', 'Egyptian',
       'Latin, Central or South American, n.o.s.', 'Tamil', 'Icelandic',
       'Colombian', 'Moroccan', 'Czech', 'Syrian', 'Guyanese', 'Afghan',
       'Black, n.o.s.', 'Serbian', 'Ojibway', 'Newfoundlander',
       'Hong Konger', 'Ontarian', 'Persian', 'Trinidadian/Tobagonian',
       'Turkish', 'Inuit, n.o.s.', 'Bangladeshi', 'Algerian', 'Brazilian',
       'Nigerian', 'Armenian', 'Slovak', 'Eastern European, n.o.s.',
       'Somali', 'Taiwanese', 'Iraqi', 'Salvadorean', 'African Caribbean',
       'East or Southeast Asian, n.o.s.',
       'West or Central Asian or Middle Eastern, n.o.s.',
       'Caribbean, n.o.s.', 'Algonquin', 'West Indian, n.o.s.',
       'Lithuanian', 'South African', 'Australian', 'Palestinian',
       'Chilean', 'Congolese', 'Nova Scotian', 'Ethiopian',
       'Hispanic, n.o.s.', 'Peruvian', 'Yoruba', 'Cambodian (Khmer)',
       'Berber', 'Albanian', 'Maltese', 'Macedonian', 'Slovenian',
       'Western European, n.o.s.', 'New Brunswicker', 'Gujarati',
       'Eritrean', 'African Canadian', 'Israeli', 'Mohawk',
       'Czechoslovakian, n.o.s.', 'Bulgarian', 'Albertan', 'Ghanaian',
       'Barbadian', 'African American', 'Yugoslavian, n.o.s.', 'Tunisian',
       'Slavic, n.o.s.', 'Cuban', 'Bosnian', 'Venezuelan',
       'Innu/Montagnais, n.o.s.', 'Latvian', 'Bengali', 'Cameroonian',
       'Guatemalan', 'Indonesian', 'Laotian', 'Ilocano', 'Northern Irish',
       'Celtic, n.o.s.', 'British Columbian', 'Ecuadorian',
       'Franco Ontarian', 'Argentinian', 'Estonian', 'Kurdish', 'Fijian',
       'Jatt', 'North American, n.o.s.', 'Coptic', 'Thai', 'Dominican',
       'Nepali', 'Kabyle', 'Assyrian', 'Igbo', 'Byelorussian',
       'Dene, n.o.s.', 'Blackfoot, n.o.s.', 'Abenaki', 'Moldovan',
       'Iroquois (Haudenosaunee), n.o.s.', 'New Zealander', 'Sudanese',
       'Breton', 'Pennsylvania Dutch', 'Malaysian', 'Plains Cree',
       'North African, n.o.s.', 'Huron (Wendat)', 'Saskatchewanian',
       'Buddhist', 'Gaspesian', 'Norman',
       'Southern or East African, n.o.s.', 'Ivorian', 'Saulteaux',
       'Anishinaabe, n.o.s.', 'Burundian', 'Tigrinya', 'Nicaraguan',
       'Mauritian', 'Kenyan', 'Oji-Cree', 'Vincentian', 'Jordanian',
       'Manitoban', 'Cape Bretoner', 'Rwandan', 'Grenadian', 'Malayali',
       'Chaldean', 'Sinhalese', 'Mayan', 'Honduran', 'Cherokee',
       "Qalipu Mi'kmaq", 'Indo-Caribbean', 'Flemish',
       'United Empire Loyalist', 'Senegalese', 'Azerbaijani', 'Sicilian',
       'Pashtun', 'Malay', 'Goan', 'Bantu, n.o.s.', 'Tibetan',
       'Zimbabwean', 'Burmese', 'Mongolian', 'Azorean', 'Atikamekw',
       'Bamileke', 'Indo-Guyanese', 'Ugandan', 'Oromo', 'Tanzanian',
       'Yemeni', 'Central African', 'Libyan', 'Basque', 'Uruguayan',
       'Akan, n.o.s.', 'Central or West African, n.o.s.', 'Igorot',
       'Fulani', 'Woodland Cree', 'Guinean', 'St. Lucian',
       'Prince Edward Islander', 'Maliseet', 'Beninese', 'Telugu', 'Roma',
       'Costa Rican', 'African Nova Scotian', 'Malagasy', 'Kashmiri',
       'Singaporean', 'Karen', 'Edo', 'Tajik', 'Amhara', 'Paraguayan',
       'South Asian', 'Black', 'Latin American', 'Arab',
       'Southeast Asian', 'West Asian', 'Visible minority, n.i.e.',
       'Multiple visible minorities', 'Not a visible minority',
       'North American Aboriginal origins',
       'First Nations (North American Indian)', 'Inuit',
       'Other North American origins',
       'Other North American origins, n.i.e.', 'European origins',
       'British Isles origins', 'Channel Islander', 'Cornish', 'Manx',
       'British Isles origins, n.i.e.', 'French origins', 'Alsatian',
       'Corsican', 'French',
       'Western European origins (except French origins)', 'Bavarian',
       'Frisian', 'Luxembourger', 'Western European origins, n.i.e.',
       'Northern European origins (except British Isles origins)',
       'Northern European origins, n.i.e.', 'Eastern European origins',
       'Eastern European origins, n.i.e.', 'Southern European origins',
       'Catalan', 'Cypriot', 'Kosovar', 'Montenegrin',
       'Southern European origins, n.i.e.', 'Other European origins',
       'Roma (Gypsy)', 'Other European origins, n.i.e.',
       'Caribbean origins', 'Antiguan', 'Bahamian', 'Bermudan', 'Carib',
       'Guadeloupean', 'Kittitian/Nevisian', 'Martinican', 'Montserratan',
       'Puerto Rican', 'Vincentian/Grenadinian',
       'Caribbean origins, n.i.e.',
       'Latin, Central and South American origins',
       'Aboriginal from Central/South America (except Arawak and Maya)',
       'Arawak', 'Belizean', 'Bolivian', 'Hispanic', 'Maya', 'Panamanian',
       'Latin, Central and South American origins, n.i.e.',
       'African origins', 'Central and West African origins', 'Akan',
       'Angolan', 'Ashanti', 'Burkinabe', 'Chadian', 'Ewe', 'Gabonese',
       'Gambian', 'Ibo', 'Liberian', 'Malian', 'Malinké', 'Peulh',
       'Sierra Leonean', 'Togolese', 'Wolof',
       'Central and West African origins, n.i.e.',
       'North African origins', 'Dinka', 'Maure',
       'North African origins, n.i.e.',
       'Southern and East African origins', 'Afrikaner', 'Djiboutian',
       'Harari', 'Seychellois', 'Tigrian', 'Zambian', 'Zulu',
       'Southern and East African origins, n.i.e.',
       'Other African origins', 'Other African origins, n.i.e.',
       'Asian origins', 'West Central Asian and Middle Eastern origins',
       'Georgian', 'Hazara', 'Kazakh', 'Kurd', 'Kuwaiti', 'Kyrgyz',
       'Saudi Arabian', 'Tatar', 'Turk', 'Turkmen', 'Uighur', 'Uzbek',
       'West Central Asian and Middle Eastern origins, n.i.e.',
       'South Asian origins', 'Bhutanese', 'East Indian',
       'South Asian origins, n.i.e.', 'East and Southeast Asian origins',
       'Hmong', 'East and Southeast Asian origins, n.i.e.',
       'Other Asian origins', 'Other Asian origins, n.i.e.',
       'Oceania origins', 'Pacific Islands origins', 'Hawaiian', 'Maori',
       'Samoan', 'Polynesian, n.o.s.', 'Pacific Islands origins, n.i.e.'],
      dtype=object)

### Mapping and transform

In [129]:
def map_ethnicity(variable: str) -> str | None:
    v = str(variable).strip().lower()

    # Indigenous
    if any(x in v for x in [
        "first nations", "north american indian", "métis", "metis", "inuit",
        "cree", "ojib", "algonquin", "anishinaabe", "iroquois", "haudenosaunee",
        "dene", "blackfoot", "mohawk", "maliseet", "mi'kmaq", "mikmaq",
        "huron", "wendat", "innu", "montagnais", "oji-cree", "saulteaux",
        "abenaki", "atikamekw", "cherokee", "maya", "mayan", "qalipu"
    ]):
        return "indigenous"

    # South Asian
    if any(x in v for x in [
        "indian", "east indian", "pakistani", "punjabi", "tamil", "bengali",
        "bangladeshi", "sri lankan", "gujarati", "nepali", "goan",
        "kashmiri", "telugu", "sinhalese", "malayali", "jatt", "south asian"
    ]):
        return "south_asian"

    # East / Southeast Asian
    if any(x in v for x in [
        "chinese", "filipino", "vietnamese", "korean", "japanese", "thai",
        "cambodian", "khmer", "laotian", "indonesian", "malaysian", "taiwanese",
        "hong konger", "singaporean", "burmese", "mongolian", "tibetan",
        "hmong", "igorot", "ilocano", "east and southeast asian",
        "east or southeast asian", "southeast asian"
    ]):
        return "east_se_asian"

    # Black / African / Caribbean
    if any(x in v for x in [
        "african", "black", "jamaican", "haitian", "nigerian", "somali",
        "ethiopian", "ghanaian", "cameroonian", "congolese", "sudanese",
        "rwandan", "burundian", "kenyan", "ugandan", "tanzanian", "zimbabwean",
        "ivorian", "senegalese", "guinean", "beninese", "libyan", "yoruba",
        "igbo", "ibo", "akan", "ashanti", "ewe", "fulani", "wolof", "oromo",
        "amhara", "bantu", "tigrinya", "tigrian", "dinka", "harari", "edo",
        "african caribbean", "african canadian", "african american",
        "african nova scotian", "caribbean", "west indian", "barbadian",
        "grenadian", "vincentian", "vincentian/grenadinian", "st. lucian",
        "trinidadian", "tobagonian", "indo-caribbean", "indo-guyanese"
    ]):
        return "black"

    # Middle Eastern / West Asian / Arab
    if any(x in v for x in [
        "arab", "iranian", "persian", "lebanese", "afghan", "turkish",
        "iraqi", "palestinian", "syrian", "egyptian", "algerian", "moroccan",
        "tunisian", "yemeni", "jordanian", "israeli", "armenian", "assyrian",
        "chaldean", "kurd", "kazakh", "kyrgyz", "uzbek", "uighur", "turkmen",
        "azerbaijani", "tajik", "georgian", "hazara", "saudi", "kuwaiti",
        "west asian", "west central asian", "middle eastern",
        "west or central asian or middle eastern"
    ]):
        return "middle_eastern"

    # Latin American
    if any(x in v for x in [
        "mexican", "brazilian", "colombian", "peruvian", "chilean", "cuban",
        "venezuelan", "ecuadorian", "argentinian", "guatemalan", "salvadorean",
        "dominican", "nicaraguan", "honduran", "paraguayan", "uruguayan",
        "costa rican", "panamanian", "bolivian", "belizean", "puerto rican",
        "latin american", "latin, central or south american",
        "latin, central and south american", "hispanic"
    ]):
        return "latin_american"

    # European / White
    if any(x in v for x in [
        "canadian", "québécois", "quebecois", "french canadian", "acadian",
        "english", "irish", "scottish", "welsh", "british", "british isles",
        "northern irish", "channel islander", "cornish", "manx", "celtic",
        "french", "alsatian", "corsican", "gaspesian", "norman",
        "german", "bavarian", "dutch", "flemish", "belgian", "luxembourger",
        "swiss", "austrian", "finnish", "swedish", "norwegian", "danish",
        "icelandic", "frisian", "northern european", "western european",
        "european", "caucasian", "white",
        "italian", "sicilian", "maltese", "portuguese", "spanish", "catalan",
        "greek", "cypriot", "albanian", "macedonian", "slovenian", "croatian",
        "serbian", "bosnian", "montenegrin", "kosovar", "romanian", "hungarian",
        "czech", "slovak", "polish", "ukrainian", "russian", "lithuanian",
        "latvian", "estonian", "bulgarian", "moldovan", "byelorussian",
        "slavic", "yugoslavian", "czechoslovakian", "eastern european",
        "southern european", "roma", "gypsy", "basque", "breton",
        "newfoundlander", "nova scotian", "new brunswicker", "ontarian",
        "albertan", "saskatchewanian", "manitoban", "british columbian",
        "prince edward islander", "cape bretoner", "franco ontarian",
        "north american, n.o.s.", "other north american origins"
    ]):
        return "european"

    # Oceania
    if any(x in v for x in [
        "australian", "new zealander", "fijian", "hawaiian", "maori",
        "samoan", "polynesian", "pacific islands", "oceania"
    ]):
        return "other"

    return "other"


def is_ethnicity_aggregate(variable: str) -> bool:
    v = str(variable).strip().lower()

    aggregate_patterns = [
        "total -",
        "visible minority",
        "multiple visible minorities",
        "origins",
        "n.o.s.",
        "n.i.e.",
    ]

    return any(p in v for p in aggregate_patterns)


def transform_ethnicity(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["variable"] = df["variable"].astype(str).str.strip()

    # Drop aggregate / rollup / alternate-taxonomy rows before mapping
    df = df[~df["variable"].apply(is_ethnicity_aggregate)].copy()

    df["ethnicity_group"] = df["variable"].apply(map_ethnicity)

    grouped = (
        df.groupby(["geography", "year", "ethnicity_group"], as_index=False)["value"]
        .sum()
    )

    grouped["total"] = grouped.groupby(["geography", "year"])["value"].transform("sum")
    grouped["pct"] = grouped["value"] / grouped["total"]

    wide = (
        grouped.pivot(index=["geography", "year"], columns="ethnicity_group", values="pct")
        .reset_index()
        .rename(columns={
            "indigenous": "pct_indigenous",
            "european": "pct_european",
            "south_asian": "pct_south_asian",
            "east_se_asian": "pct_east_se_asian",
            "black": "pct_black",
            "middle_eastern": "pct_middle_eastern",
            "latin_american": "pct_latin_american",
            "other": "pct_other",
        })
    )

    wide.columns.name = None
    return wide


def check_unmapped_ethnicity_variables(df: pd.DataFrame) -> pd.DataFrame:
    check = df.copy()
    check["variable"] = check["variable"].astype(str).str.strip()
    check = check[~check["variable"].apply(is_ethnicity_aggregate)].copy()
    check["ethnicity_group"] = check["variable"].apply(map_ethnicity)

    return (
        check.groupby(["variable", "ethnicity_group"], as_index=False)
        .agg(rows=("variable", "size"), total_value=("value", "sum"))
        .sort_values(["ethnicity_group", "total_value", "variable"], ascending=[True, False, True])
    )
def check_missing_output_columns(wide_df: pd.DataFrame) -> list[str]:
    expected = [
        "pct_indigenous",
        "pct_european",
        "pct_south_asian",
        "pct_east_se_asian",
        "pct_black",
        "pct_middle_eastern",
        "pct_latin_american",
        "pct_other",
    ]
    return [c for c in expected if c not in wide_df.columns]

In [130]:
ethnicity_wide = transform_ethnicity(ethnic)

mapping_check = check_unmapped_ethnicity_variables(ethnic)
missing_cols = check_missing_output_columns(ethnicity_wide)

print(mapping_check.head(20))
print("Missing output columns:", missing_cols)

                   variable ethnicity_group  rows  total_value
43                    Black           black    50       504850
143                Jamaican           black    50       152095
247                  Somali           black    50        40780
269  Trinidadian/Tobagonian           black    50        37575
168              Macedonian           black    50        24920
90                Ethiopian           black    50        24165
200                Nigerian           black    50        20585
107                Ghanaian           black    50        17505
33                Barbadian           black    50        15370
6         African Caribbean           black    25        15290
110               Grenadian           black    50        12425
248           South African           black    50        10940
289                  Yoruba           black    50         6520
116                 Haitian           black    50         6240
283  Vincentian/Grenadinian           black    25         6165
5          African Canadian           black    25         6015
253              St. Lucian           black    50         5995
69                Congolese           black    50         5330
254                Sudanese           black    50         4510
4          African American           black    25         4430
Missing output columns: []

In [132]:
ethnicity_wide[ethnicity_wide['geography']=='Ward 1']

,geography,year,pct_black,pct_east_se_asian,pct_european,pct_indigenous,pct_latin_american,pct_middle_eastern,pct_other,pct_south_asian
0,Ward 1,2016,0.235017,0.086725,0.221273,0.004193,0.051568,0.068429,0.021008,0.311787
1,Ward 1,2021,0.239226,0.099762,0.178947,0.001672,0.040792,0.089389,0.049615,0.300596

## Family Transformation 4/8

families_long

In [176]:
fam = data['families_long']
print(ds.quick_summary(fam))
fam[fam['geography']=='Ward 1']
fam.variable.unique()

             dtype  col_index  missing_pct  n_unique
variable    object          0          0.0        46
geography   object          1          0.0        26
value      float64          2          0.0      1792
year         int64          3          0.0         3
category    object          4          0.0         1

array(['Total children in census families in private households',
       'Under 6 years of age', '6 to 14 years', '15 to 17 years',
       '18 to 24 years', '25 years and over',
       'Total number of census families in private households - 25% sample data',
       'Total couple families', 'Married couples',
       'With children at home', 'Without children at home',
       'Common-law couples', 'Total one-parent families',
       'in which the parent is a woman+', 'in which the parent is a man+',
       'Total - Household type - 25% sample data',
       'One-census-family households without additional persons',
       'Couple-family households', 'One-parent-family households',
       'Multigenerational households',
       'Multiple-census-family households',
       'One-census-family households with additional persons',
       'Two-or-more-person non-census-family households', '1 person',
       'Total - Private households by household size - 25% sample data',
       '2 persons', '3 persons', '4 persons', '5 or more persons',
       'Number of persons in private households',
       'Average household size',
       'Total - Couple census families in private households - 25% sample data',
       'Couples without children', 'Couples with children', '1 child',
       '2 children', '3 or more children',
       'Total - Lone-parent census families in private households - 25% sample data',
       'Total - Private households by household type - 25% sample data',
       'One-census-family households', 'Non-census-family households',
       'Total number of census families in private households',
       'Total couple families by family structure and number of children',
       'Total lone-parent families by sex of parent and number of children',
       'Female parent', 'Male parent'], dtype=object)

In [177]:
fam = fam[~fam["geography"].str.contains("toronto", case=False, na=False)].reset_index(drop=True) # drop geography = Toronto

In [178]:
fam['variable'].unique()

array(['Total children in census families in private households',
       'Under 6 years of age', '6 to 14 years', '15 to 17 years',
       '18 to 24 years', '25 years and over',
       'Total number of census families in private households - 25% sample data',
       'Total couple families', 'Married couples',
       'With children at home', 'Without children at home',
       'Common-law couples', 'Total one-parent families',
       'in which the parent is a woman+', 'in which the parent is a man+',
       'Total - Household type - 25% sample data',
       'One-census-family households without additional persons',
       'Couple-family households', 'One-parent-family households',
       'Multigenerational households',
       'Multiple-census-family households',
       'One-census-family households with additional persons',
       'Two-or-more-person non-census-family households', '1 person',
       'Total - Private households by household size - 25% sample data',
       '2 persons', '3 persons', '4 persons', '5 or more persons',
       'Number of persons in private households',
       'Average household size',
       'Total - Couple census families in private households - 25% sample data',
       'Couples without children', 'Couples with children', '1 child',
       '2 children', '3 or more children',
       'Total - Lone-parent census families in private households - 25% sample data',
       'Total - Private households by household type - 25% sample data',
       'One-census-family households', 'Non-census-family households',
       'Total number of census families in private households',
       'Total couple families by family structure and number of children',
       'Total lone-parent families by sex of parent and number of children',
       'Female parent', 'Male parent'], dtype=object)

In [195]:
fam2021= fam[(fam["geography"] == "Ward 1") & (fam["year"] == 2021)]
fam2016= fam[(fam["geography"] == "Ward 1") & (fam["year"] == 2016)]

In [211]:
fam2016.variable.unique()

array(['Total - Couple census families in private households - 25% sample data',
       'Couples without children', 'Couples with children', '1 child',
       '2 children', '3 or more children',
       'Total - Lone-parent census families in private households - 25% sample data',
       'Total children in census families in private households',
       'Under 6 years of age', '6 to 14 years', '15 to 17 years',
       '18 to 24 years', '25 years and over',
       'Total - Private households by household type - 25% sample data',
       'One-census-family households',
       'Multiple-census-family households',
       'Non-census-family households',
       'Total - Private households by household size - 25% sample data',
       '1 person', '2 persons', '3 persons', '4 persons',
       '5 or more persons', 'Number of persons in private households',
       'Average household size'], dtype=object)

### Mapping, Transform, and backfill

for 2016, it was manually calculated the number of households with children and without children through raw count numbers of # of childrens iin census data

In [219]:
def transform_family_households(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["variable"] = df["variable"].astype(str).str.strip()
    df["value"] = pd.to_numeric(df["value"], errors="coerce")

    child_age_map = {
        "Under 6 years of age": "children_under_6",
        "6 to 14 years": "children_6_14",
        "15 to 17 years": "children_15_17",
        "18 to 24 years": "children_18_24",
        "25 years and over": "children_25_plus",
    }

    child_count_map = {
        "1 child": "1_child",
        "2 children": "2_children",
        "3 or more children": "3plus_children",
    }

    def compute_pct(subset: pd.DataFrame, group_col: str) -> pd.DataFrame:
        grouped = (
            subset.groupby(["geography", "year", group_col], as_index=False)["value"]
            .sum()
        )
        grouped["denominator"] = grouped.groupby(["geography", "year"])["value"].transform("sum")
        grouped["pct"] = grouped["value"] / grouped["denominator"]

        return (
            grouped.pivot(index=["geography", "year"], columns=group_col, values="pct")
            .reset_index()
            .rename_axis(None, axis=1)
        )

    # children age distribution
    age_df = df[df["variable"].isin(child_age_map)].copy()
    age_df["child_age_group"] = age_df["variable"].map(child_age_map)
    age_wide = compute_pct(age_df, "child_age_group")

    # children count distribution among couple families with children
    count_df = df[df["variable"].isin(child_count_map)].copy()
    count_df["child_count_group"] = count_df["variable"].map(child_count_map)
    count_wide = compute_pct(count_df, "child_count_group")

    # pct_with_children, using year-specific available schema
    couple_2016 = df[df["variable"].isin([
        "Couples without children",
        "Couples with children",
    ])].copy()
    
    couple_2016_wide = (
        couple_2016.pivot_table(
            index=["geography", "year"],
            columns="variable",
            values="value",
            aggfunc="sum"
        )
        .reset_index()
    )
    
    if {"Couples with children", "Couples without children"}.issubset(couple_2016_wide.columns):
        couple_2016_wide["pct_with_children"] = (
            couple_2016_wide["Couples with children"] /
            (
                couple_2016_wide["Couples with children"]
                + couple_2016_wide["Couples without children"]
            )
        )
        couple_2016_wide = couple_2016_wide[["geography", "year", "pct_with_children"]]
    else:
        couple_2016_wide = pd.DataFrame(columns=["geography", "year", "pct_with_children"])
    
    
    couple_2021 = df[df["variable"].isin([
        "With children at home",
        "Without children at home",
    ])].copy()
    
    couple_2021_wide = (
        couple_2021.pivot_table(
            index=["geography", "year"],
            columns="variable",
            values="value",
            aggfunc="sum"
        )
        .reset_index()
    )
    
    if {"With children at home", "Without children at home"}.issubset(couple_2021_wide.columns):
        couple_2021_wide["pct_with_children"] = (
            couple_2021_wide["With children at home"] /
            (
                couple_2021_wide["With children at home"]
                + couple_2021_wide["Without children at home"]
            )
        )
        couple_2021_wide = couple_2021_wide[["geography", "year", "pct_with_children"]]
    else:
        couple_2021_wide = pd.DataFrame(columns=["geography", "year", "pct_with_children"])
    
    
    couple_wide = pd.concat(
        [couple_2016_wide, couple_2021_wide],
        ignore_index=True
    ).drop_duplicates(
        subset=["geography", "year"],
        keep="first"
    )

    couple_wide = couple_wide[["geography", "year", "pct_with_children"]]

    final = (
        age_wide
        .merge(count_wide, on=["geography", "year"], how="outer")
        .merge(couple_wide, on=["geography", "year"], how="outer")
    )

    final = final.rename(columns={
        "children_under_6": "pct_children_under_6",
        "children_6_14": "pct_children_6_14",
        "children_15_17": "pct_children_15_17",
        "children_18_24": "pct_children_18_24",
        "children_25_plus": "pct_children_25_plus",
        "1_child": "pct_1_child",
        "2_children": "pct_2_children",
        "3plus_children": "pct_3plus_children",
    })

    pct_cols = [c for c in final.columns if c.startswith("pct_")]
    final[pct_cols] = final[pct_cols].fillna(pd.NA)
    # VALIDATION
    age_ok = final[[
        "pct_children_under_6",
        "pct_children_6_14",
        "pct_children_15_17",
        "pct_children_18_24",
        "pct_children_25_plus",
    ]].sum(axis=1).between(0.99, 1.01)
    
    count_ok = final[[
        "pct_1_child",
        "pct_2_children",
        "pct_3plus_children",
    ]].sum(axis=1).between(0.99, 1.01) | final["year"].ne(2016)
    
    pct_ok = final["pct_with_children"].between(0, 1) | final["pct_with_children"].isna()
    
    if not (age_ok & count_ok & pct_ok).all():
        raise ValueError("Family validation failed")
    return final

In [220]:
family_wide = transform_family_households(fam)
#validation = validate_family_households_output(family_wide)
#unmapped = check_unmapped_family_variables(fam)

In [221]:
family_wide[family_wide['year']==2021].head()

,geography,year,pct_children_15_17,pct_children_18_24,pct_children_25_plus,pct_children_6_14,pct_children_under_6,pct_1_child,pct_2_children,pct_3plus_children,pct_with_children
2,Ward 1,2021,0.097406,0.216038,0.253656,0.267689,0.165212,NaN,NaN,NaN,0.645853
5,Ward 10,2021,0.066980,0.143975,0.210955,0.267606,0.310485,NaN,NaN,NaN,0.258479
8,Ward 11,2021,0.093794,0.199490,0.198073,0.300085,0.208558,NaN,NaN,NaN,0.369798
11,Ward 12,2021,0.106669,0.194456,0.158899,0.320209,0.219767,NaN,NaN,NaN,0.426980
14,Ward 13,2021,0.088135,0.196520,0.188534,0.276098,0.250713,NaN,NaN,NaN,0.314282

## Households transformations 5/8
households_long

In [237]:
house = data['households_long']
print(ds.quick_summary(house))
#house = drop_totals(house)

             dtype  col_index  missing_pct  n_unique
variable    object          0          0.0        38
geography   object          1          0.0        26
value      float64          2          0.0       882
year         int64          3          0.0         1
category    object          4          0.0         1

In [243]:
house.year.unique()

array([2011])

In [261]:
house[house['geography']=='Ward 1']

,variable,geography,value,year,category
0,Total number of occupied private dwellings by ...,Ward 1,37085.0,2011,households
1,Single-detached house,Ward 1,11580.0,2011,households
2,Semi-detached house,Ward 1,1330.0,2011,households
3,Row house,Ward 1,3620.0,2011,households
4,"Apartment, duplex",Ward 1,3475.0,2011,households
5,"Apartment, building that has five or more storeys",Ward 1,15215.0,2011,households
6,"Apartment, building that has fewer than five s...",Ward 1,1860.0,2011,households
7,Other single-attached house,Ward 1,5.0,2011,households
8,Movable dwelling,Ward 1,0.0,2011,households
9,Total number of private households by househol...,Ward 1,37085.0,2011,households
10,Census family households,Ward 1,28550.0,2011,households
11,One-family only households,Ward 1,22560.0,2011,households
12,Couple family households,Ward 1,17095.0,2011,households
13,Without children,Ward 1,5305.0,2011,households
14,With children,Ward 1,11790.0,2011,households
15,Lone-parent family households,Ward 1,5465.0,2011,households
16,Other family households,Ward 1,5985.0,2011,households
17,One-family households with persons not in a ce...,Ward 1,3380.0,2011,households
18,Couple family households,Ward 1,2195.0,2011,households
19,Without children,Ward 1,555.0,2011,households
20,With children,Ward 1,1635.0,2011,households
21,Lone-parent family households,Ward 1,1185.0,2011,households
22,Two-or-more-family households,Ward 1,2605.0,2011,households
23,Non-census family households,Ward 1,8540.0,2011,households
24,One-person households,Ward 1,6795.0,2011,households
25,Two-or-more-person households,Ward 1,1745.0,2011,households
26,Total number of private households by househol...,Ward 1,37085.0,2011,households
27,1 person,Ward 1,6800.0,2011,households
28,2 persons,Ward 1,8975.0,2011,households
29,3 persons,Ward 1,7040.0,2011,households
30,4 persons,Ward 1,7125.0,2011,households
31,5 persons,Ward 1,3735.0,2011,households
32,6 or more persons,Ward 1,3415.0,2011,households
33,Total number of persons in private households,Ward 1,116260.0,2011,households
34,Average number of persons in private households,Ward 1,3.1,2011,households
35,Total - Tenure,Ward 1,37105.0,2011,households
36,Owned,Ward 1,21030.0,2011,households
37,Owned - Part of a condominium,Ward 1,6015.0,2011,households
38,Owned - Not part of a condominium,Ward 1,15020.0,2011,households
39,Rented,Ward 1,16075.0,2011,households
40,Rented - Part of a condominium,Ward 1,2450.0,2011,households
41,Rented - Not part of a condominium,Ward 1,13625.0,2011,households

In [264]:
house['variable'].unique()

array(['Total number of occupied private dwellings by structural type of dwelling',
       'Single-detached house', 'Semi-detached house', 'Row house',
       'Apartment, duplex',
       'Apartment, building that has five or more storeys',
       'Apartment, building that has fewer than five storeys',
       'Other single-attached house', 'Movable dwelling',
       'Total number of private households by household type',
       'Census family households', 'One-family only households',
       'Couple family households', 'Without children', 'With children',
       'Lone-parent family households', 'Other family households',
       'One-family households with persons not in a census family',
       'Two-or-more-family households', 'Non-census family households',
       'One-person households', 'Two-or-more-person households',
       'Total number of private households by household size', '1 person',
       '2 persons', '3 persons', '4 persons', '5 persons',
       '6 or more persons',
       'Total number of persons in private households',
       'Average number of persons in private households',
       'Total - Tenure', 'Owned', 'Owned - Part of a condominium',
       'Owned - Not part of a condominium', 'Rented',
       'Rented - Part of a condominium',
       'Rented - Not part of a condominium'], dtype=object)

In [245]:
house = house[~house["geography"].str.contains("Toronto", case=False, na=False)].reset_index(drop=True)

## Mapping, transform

In [262]:
def transform_households_wide(households_long: pd.DataFrame) -> pd.DataFrame:
    df = households_long.copy()
    raw = households_long.copy()

    # clean both
    for d in (df, raw):
        d["variable"] = d["variable"].astype(str).str.strip()
        d["value"] = pd.to_numeric(d["value"], errors="coerce")

    # ----------------------------
    # FILTER (features + totals)
    # ----------------------------
    df = df[
        df["variable"].isin(HOUSEHOLDS_FEATURE_MAP)
        | df["variable"].str.contains("Total|Number of", case=False, na=False)
    ].copy()

    df["feature"] = df["variable"].map(HOUSEHOLDS_FEATURE_MAP)
    df["denominator_variable"] = df["variable"].map(HOUSEHOLDS_DENOMINATOR_MAP)

    # ----------------------------
    # DENOMINATORS
    # ----------------------------
    denom = (
        df.groupby(["geography", "year", "denominator_variable"], as_index=False)["value"]
        .sum()
        .rename(columns={"value": "denominator_value"})
    )

    df = df.merge(
        denom,
        on=["geography", "year", "denominator_variable"],
        how="left"
    )

    df["pct_value"] = df["value"] / df["denominator_value"]

    # ----------------------------
    # BASE FEATURES
    # ----------------------------
    wide = (
        df.groupby(["geography", "year", "feature"], as_index=False)["pct_value"]
        .sum()
        .pivot_table(
            index=["geography", "year"],
            columns="feature",
            values="pct_value",
            aggfunc="sum"
        )
        .reset_index()
    )

    wide.columns.name = None

    # ----------------------------
    # CHILDREN (MAIN BLOCK ONLY)
    # ----------------------------
    fam = raw.sort_values(["geography", "year"]).reset_index(drop=True)

    mask = fam["variable"] == "Census family households"

    blocks = []
    for i in fam.index[mask]:
        blocks.append(fam.loc[i:i+5])  # fixed structure

    fam_block = pd.concat(blocks)

    fam_block = fam_block[fam_block["variable"].isin([
        "Census family households",
        "Couple family households",
        "With children",
        "Without children",
        "Lone-parent family households",
    ])]

    fam_wide = (
        fam_block.pivot_table(
            index=["geography", "year"],
            columns="variable",
            values="value",
            aggfunc="first"
        )
        .reset_index()
    )

    # safe computation
    if all(col in fam_wide.columns for col in [
        "Census family households",
        "With children",
        "Without children",
        "Lone-parent family households",
    ]):
        fam_wide["pct_with_children"] = (
            fam_wide["With children"]
            + fam_wide["Lone-parent family households"]
        ) / fam_wide["Census family households"]

        fam_wide["pct_without_children"] = (
            fam_wide["Without children"]
        ) / fam_wide["Census family households"]

        fam_wide["pct_single_parent"] = (
            fam_wide["Lone-parent family households"]
            / (
                fam_wide["With children"]
                + fam_wide["Lone-parent family households"]
            )
        )

        fam_wide = fam_wide[[
            "geography",
            "year",
            "pct_with_children",
            "pct_without_children",
            "pct_single_parent",
        ]]

        wide = wide.merge(fam_wide, on=["geography", "year"], how="left")

    # ----------------------------
    # FINAL ORDER
    # ----------------------------
    ordered_cols = [
        "geography",
        "year",

        "pct_1_person",
        "pct_2_person",
        "pct_3_person",
        "pct_4_person",
        "pct_5plus_person",

        "pct_with_children",
        "pct_without_children",
        "pct_single_parent",

        "pct_multi_family",
        "pct_non_family",

        "pct_detached",
        "pct_attached/other",
        "pct_apartment",
        "pct_condo",
        "pct_non_condo",
    ]

    for col in ordered_cols:
        if col not in wide.columns:
            wide[col] = pd.NA

    return wide[ordered_cols]

In [263]:
house_trans = transform_households_wide(house)
house_trans

,geography,year,pct_1_person,pct_2_person,pct_3_person,pct_4_person,pct_5plus_person,pct_with_children,pct_without_children,pct_single_parent,pct_multi_family,pct_non_family,pct_detached,pct_attached/other,pct_apartment,pct_condo,pct_non_condo
0,Ward 1,2011,0.183338,0.241979,0.189809,0.192100,0.192774,0.604378,0.185814,0.316720,0.233737,0.766263,0.312256,0.227316,0.460429,0.228106,0.771894
1,Ward 10,2011,0.519724,0.337646,0.083457,0.036267,0.022906,0.345638,0.576063,0.384304,0.015144,0.984856,0.012301,0.088229,0.899470,0.718432,0.281568
2,Ward 11,2011,0.440247,0.329950,0.111030,0.075555,0.043219,0.427628,0.477133,0.282800,0.020457,0.979543,0.091765,0.167312,0.740923,0.255308,0.744692
3,Ward 12,2011,0.467088,0.304918,0.107444,0.079315,0.041236,0.479162,0.439114,0.296988,0.014079,0.985921,0.174146,0.103435,0.722419,0.360172,0.639828
4,Ward 13,2011,0.548737,0.302525,0.081848,0.041639,0.025250,0.428728,0.501778,0.425016,0.008263,0.991737,0.005050,0.064310,0.930640,0.175074,0.824926
5,Ward 14,2011,0.350218,0.309383,0.155305,0.121611,0.063483,0.545644,0.339723,0.301565,0.045983,0.954017,0.195604,0.333742,0.470654,0.053412,0.946588
6,Ward 15,2011,0.304237,0.280373,0.150204,0.162966,0.102221,0.617545,0.302866,0.195359,0.040575,0.959425,0.381876,0.117294,0.500830,0.112967,0.887033
7,Ward 16,2011,0.303550,0.300359,0.171254,0.137748,0.087089,0.608394,0.283619,0.320161,0.063754,0.936246,0.149541,0.142230,0.708228,0.288070,0.711930
8,Ward 17,2011,0.221390,0.295756,0.216397,0.171725,0.094731,0.591176,0.272371,0.239844,0.119132,0.880868,0.240999,0.229435,0.529566,0.300092,0.699908
9,Ward 18,2011,0.300966,0.315888,0.180492,0.137371,0.065284,0.552921,0.329038,0.251088,0.062642,0.937358,0.278284,0.083397,0.638319,0.513543,0.486457
10,Ward 19,2011,0.333005,0.300832,0.167980,0.137229,0.060954,0.597340,0.308333,0.298011,0.036629,0.963371,0.284933,0.230332,0.484736,0.090740,0.909260
11,Ward 2,2011,0.239972,0.313297,0.182393,0.175497,0.088840,0.599086,0.299543,0.254211,0.074961,0.925039,0.505229,0.081945,0.412826,0.182257,0.817743
12,Ward 20,2011,0.282697,0.285030,0.175488,0.156331,0.100454,0.610574,0.249407,0.327262,0.084051,0.915949,0.367678,0.183716,0.448606,0.101485,0.898515
13,Ward 21,2011,0.242278,0.287530,0.185585,0.156985,0.127622,0.584121,0.243354,0.316432,0.132950,0.867050,0.359731,0.179357,0.460913,0.224472,0.775528
14,Ward 22,2011,0.187294,0.270282,0.217342,0.177851,0.147231,0.570930,0.227306,0.259414,0.225338,0.774662,0.326942,0.203176,0.469881,0.332857,0.667143
15,Ward 23,2011,0.117707,0.227250,0.212791,0.218064,0.224188,0.568471,0.168989,0.234594,0.410714,0.589286,0.403912,0.320578,0.275510,0.280415,0.719585
16,Ward 24,2011,0.226219,0.274132,0.184066,0.174090,0.141492,0.608488,0.227108,0.327364,0.147445,0.852555,0.346213,0.146691,0.507096,0.205420,0.794580
17,Ward 25,2011,0.147826,0.243953,0.193518,0.215178,0.199526,0.589528,0.202370,0.246353,0.292477,0.707523,0.561126,0.279140,0.159734,0.140509,0.859491
18,Ward 3,2011,0.368871,0.325067,0.145287,0.110224,0.050551,0.539309,0.374291,0.303577,0.031563,0.968437,0.350622,0.096039,0.553339,0.236132,0.763868
19,Ward 4,2011,0.403104,0.298810,0.137920,0.111743,0.048422,0.555599,0.356654,0.288076,0.019616,0.980384,0.186698,0.162391,0.650910,0.108273,0.891727
20,Ward 5,2011,0.284882,0.278835,0.182755,0.147816,0.105711,0.619200,0.223100,0.396144,0.093645,0.906355,0.304177,0.144249,0.551574,0.127542,0.872458
21,Ward 6,2011,0.266204,0.293833,0.181747,0.153856,0.104360,0.570204,0.269575,0.305713,0.097847,0.902153,0.272525,0.160162,0.567313,0.162979,0.837021
22,Ward 7,2011,0.208437,0.262614,0.188999,0.170940,0.169010,0.596223,0.189613,0.408616,0.182463,0.817537,0.129877,0.332414,0.537709,0.142206,0.857794
23,Ward 8,2011,0.311675,0.281293,0.149863,0.151684,0.105485,0.594838,0.288139,0.260327,0.044539,0.955461,0.396518,0.111162,0.492320,0.138924,0.861076
24,Ward 9,2011,0.292457,0.306448,0.179440,0.135401,0.086253,0.549635,0.286165,0.302693,0.083938,0.916062,0.165714,0.276189,0.558097,0.058652,0.941348

In [247]:
house['variable'].value_counts()
house

,variable,geography,value,year,category
0,Total number of occupied private dwellings by ...,Ward 1,37085.0,2011,households
1,Single-detached house,Ward 1,11580.0,2011,households
2,Semi-detached house,Ward 1,1330.0,2011,households
3,Row house,Ward 1,3620.0,2011,households
4,"Apartment, duplex",Ward 1,3475.0,2011,households
...,...,...,...,...,...
1045,Owned - Part of a condominium,Ward 25,3645.0,2011,households
1046,Owned - Not part of a condominium,Ward 25,22045.0,2011,households
1047,Rented,Ward 25,5940.0,2011,households
1048,Rented - Part of a condominium,Ward 25,800.0,2011,households
1049,Rented - Not part of a condominium,Ward 25,5145.0,2011,households

### TO DO, UNION WITH DWELLINGS AND FAMILY

## Income Transformations 6/8

In [100]:
income = data['income_long']
print(ds.quick_summary(income))
income = drop_totals(income)

            dtype  col_index  missing_pct  n_unique
variable   object          0     0.000000        89
geography  object          1     0.000000        26
value      object          2     0.032864      2753
year        int64          3     0.000000         2
category   object          4     0.000000         1

In [104]:
income['variable'].unique()

array(['Total - Household total income groups in 2020 for private households - 25% sample data',
       'Under $5,000', '$5,000 to $9,999', '$10,000 to $14,999',
       '$15,000 to $19,999', '$20,000 to $24,999', '$25,000 to $29,999',
       '$30,000 to $34,999', '$35,000 to $39,999', '$40,000 to $44,999',
       '$45,000 to $49,999', '$50,000 to $59,999', '$60,000 to $69,999',
       '$70,000 to $79,999', '$80,000 to $89,999', '$90,000 to $99,999',
       '$100,000 and over', '$100,000 to $124,999',
       '$125,000 to $149,999', '$150,000 to $199,999',
       '$200,000 and over',
       'Total - Income statistics in 2020 for private households by household size - 25% sample data',
       'Average total income of households in 2020 ($)',
       'Median total income of households in 2020 ($)',
       'Total - Income statistics in 2020 for one-person private households - 25% sample data',
       'Average total income of one-person households in 2020 ($)',
       'Median total income of one-person households in 2020 ($)',
       'Total - Tenant households in non-farm, non-reserve private dwellings - 25% sample data',
       'Average monthly shelter costs for rented dwellings ($)',
       '% of tenant households spending 30% or more of its income on shelter costs',
       'Total - Owner households in non-farm, non-reserve private dwellings - 25% sample data',
       'Average monthly shelter costs for owned dwellings ($)',
       '% of owner households spending 30% or more of its income on shelter costs',
       'Total - Low-income status in 2020 for the population in private households to whom low-income concepts are applicable - 25% sample data',
       'In low income based on the Low-income measure, after-tax (LIM-AT)',
       '0 to 17 years', '18 to 64 years', '65 years and over',
       'Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)',
       'Total - Total income groups in 2020 for the population aged 15 years and over in private households - 25% sample data',
       'Without total income', 'With total income',
       'Under $10,000 (including loss)', '$10,000 to $19,999',
       '$20,000 to $29,999', '$30,000 to $39,999', '$40,000 to $49,999',
       '$100,000 to $149,999', '$150,000 and over',
       'Total - Income statistics in 2020 for the population aged 15 years and over in private households - 25% sample data',
       'Average total income in 2020 among recipients ($)',
       'Median total income in 2020 among recipients ($)',
       'Average total income for Men+ in 2020 among recipients ($)',
       'Median total income Men+ in 2020 among recipients ($)',
       'Average total income for Women+ in 2020 among recipients ($)',
       'Median total income for Women+ in 2020 among recipients ($)',
       'Gender: Total', 'Total income %', 'Market income %',
       'Employment income %', 'Wages, salaries and commissions %',
       'Net self-employment income %', 'Investment income %',
       'Private retirement income %',
       'Market income not included elsewhere %', 'Government transfers %',
       'Canada Pension Plan (CPP) and QuÚbec Pension Plan (QPP) benefits %',
       'Old Age Security pension (OAS) and Guaranteed Income Supplement (GIS) %',
       'Employment Insurance (EI) benefits %', 'Child benefits $',
       'Other government transfers %', 'Gender:   Men +',
       'Gender:   Women +',
       'Total - Household total income groups in 2015 for private households - 25% sample data',
       'Total - Income statistics in 2015 for private households by household size - 25% sample data',
       'Average total income of households in 2015 ($)',
       'Median total income of households in 2015 ($)',
       'Total - Income statistics in 2015 for one-person private households - 25% sample data',
       'Average total income of one-person households in 2015 ($)',
       'Median total income of one-person households in 2015 ($)',
       'Total - Low-income status in 2015 for the population in private households to whom low-income concepts are applicable - 25% sample data',
       'Total - Total income groups in 2015 for the population aged 15 years and over in private households - 25% sample data',
       'Total - Income statistics in 2015 for the population aged 15 years and over in private households - 25% sample data',
       'Average total income in 2015 among recipients ($)',
       'Median total income in 2015 among recipients ($)',
       'Total - Income statistics in 2015 for males aged 15 years and over in private households - 25% sample data',
       'Total - Sex', 'Sex:   Male', 'Sex:   Female'], dtype=object)

### Mapping, Transform, melt

In [106]:
import pandas as pd


INCOME_FEATURE_MAP = {
    # affordability
    "Average monthly shelter costs for rented dwellings ($)": "avg_rent_cost",
    "% of tenant households spending 30% or more of its income on shelter costs": "pct_renters_30_plus_income_on_shelter",
    "Average monthly shelter costs for owned dwellings ($)": "avg_owner_cost",
    "% of owner households spending 30% or more of its income on shelter costs": "pct_owners_30_plus_income_on_shelter",

    # poverty / low income
    "Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)": "pct_low_income_lim_at",

    # income composition
    "Employment income %": "pct_employment_income",
    "Government transfers %": "pct_government_transfers",
}


INCOME_BUCKET_MAP = {
    # low income: under 30k
    "Under $5,000": "pct_low_income",
    "$5,000 to $9,999": "pct_low_income",
    "$10,000 to $14,999": "pct_low_income",
    "$15,000 to $19,999": "pct_low_income",
    "$20,000 to $24,999": "pct_low_income",
    "$25,000 to $29,999": "pct_low_income",

    # lower-middle: 30k to 60k
    "$30,000 to $34,999": "pct_lower_mid_income",
    "$35,000 to $39,999": "pct_lower_mid_income",
    "$40,000 to $44,999": "pct_lower_mid_income",
    "$45,000 to $49,999": "pct_lower_mid_income",
    "$50,000 to $59,999": "pct_lower_mid_income",

    # middle: 60k to 100k
    "$60,000 to $69,999": "pct_mid_income",
    "$70,000 to $79,999": "pct_mid_income",
    "$80,000 to $89,999": "pct_mid_income",
    "$90,000 to $99,999": "pct_mid_income",

    # high: 100k+
    "$100,000 to $124,999": "pct_high_income",
    "$125,000 to $149,999": "pct_high_income",
    "$150,000 to $199,999": "pct_high_income",

    # very high: 150k+
    "$200,000 and over": "pct_very_high_income",
}


def transform_income_wide(income_long: pd.DataFrame) -> pd.DataFrame:
    """
    Transform income_long into a wide feature table consistent with:
    - family_wide
    - dwellings_wide
    - households_wide

    Expected input columns:
    - geography
    - year
    - variable
    - value

    Output:
    - geography
    - year
    - selected pct_* and avg_* income features
    """

    df = income_long.copy()

    df["variable"] = df["variable"].astype(str).str.strip()
    df["value"] = pd.to_numeric(df["value"], errors="coerce")

    # percentage/dollar features already provided directly
    direct = df[df["variable"].isin(INCOME_FEATURE_MAP)].copy()
    direct["feature"] = direct["variable"].map(INCOME_FEATURE_MAP)

    # convert % fields from whole-number percent to decimal
    pct_direct_features = [
        "pct_renters_30_plus_income_on_shelter",
        "pct_owners_30_plus_income_on_shelter",
        "pct_low_income_lim_at",
        "pct_employment_income",
        "pct_government_transfers",
    ]

    direct.loc[
        direct["feature"].isin(pct_direct_features),
        "value"
    ] = direct.loc[
        direct["feature"].isin(pct_direct_features),
        "value"
    ] / 100

    direct_wide = (
        direct.pivot_table(
            index=["geography", "year"],
            columns="feature",
            values="value",
            aggfunc="first"
        )
        .reset_index()
    )

    # income distribution buckets
    buckets = df[df["variable"].isin(INCOME_BUCKET_MAP)].copy()
    buckets["feature"] = buckets["variable"].map(INCOME_BUCKET_MAP)

    bucket_wide = (
        buckets.groupby(["geography", "year", "feature"], as_index=False)["value"]
        .sum()
        .pivot_table(
            index=["geography", "year"],
            columns="feature",
            values="value",
            aggfunc="sum"
        )
        .reset_index()
    )

    # If bucket values are counts, convert to percentages.
    # If they are already percentages, remove this block.
    bucket_cols = [
        "pct_low_income",
        "pct_lower_mid_income",
        "pct_mid_income",
        "pct_high_income",
        "pct_very_high_income",
    ]

    available_bucket_cols = [c for c in bucket_cols if c in bucket_wide.columns]

    if available_bucket_cols:
        bucket_total = bucket_wide[
            ["pct_low_income", "pct_lower_mid_income", "pct_mid_income", "pct_high_income"]
        ].sum(axis=1)

        for col in available_bucket_cols:
            bucket_wide[col] = bucket_wide[col] / bucket_total

    income_wide = direct_wide.merge(
        bucket_wide,
        on=["geography", "year"],
        how="outer"
    )

    income_wide.columns.name = None

    ordered_cols = [
        "geography",
        "year",

        # income distribution
        "pct_low_income",
        "pct_lower_mid_income",
        "pct_mid_income",
        "pct_high_income",
        "pct_very_high_income",

        # affordability
        "pct_renters_30_plus_income_on_shelter",
        "pct_owners_30_plus_income_on_shelter",
        "avg_rent_cost",
        "avg_owner_cost",

        # poverty
        "pct_low_income_lim_at",

        # income composition
        "pct_employment_income",
        "pct_government_transfers",
    ]

    for col in ordered_cols:
        if col not in income_wide.columns:
            income_wide[col] = pd.NA

    return income_wide[ordered_cols]

In [45]:
income_wide = transform_income_wide(income)
ds.quick_summary(income_wide)
income_wide

,geography,year,pct_low_income,pct_lower_mid_income,pct_mid_income,pct_high_income,pct_very_high_income,pct_renters_30_plus_income_on_shelter,pct_owners_30_plus_income_on_shelter,avg_rent_cost,avg_owner_cost,pct_low_income_lim_at,pct_employment_income,pct_government_transfers
0,Ward 1,2016,0.122387,0.254377,0.328064,0.295173,0.050399,0.428,0.273,1064.0,1425.0,0.225,0.718,0.193
1,Ward 1,2021,0.061058,0.217239,0.338499,0.383204,0.089766,0.342,0.235,1328.0,1664.0,0.129,0.620,0.292
2,Ward 10,2016,0.100783,0.148810,0.336421,0.413986,0.088418,0.446,0.360,1673.0,1916.0,0.173,0.877,0.034
3,Ward 10,2021,0.073140,0.125073,0.313278,0.488509,0.114913,0.437,0.352,1988.0,2290.0,0.141,0.842,0.077
4,Ward 11,2016,0.143778,0.147109,0.262983,0.446131,0.125921,0.523,0.279,1560.0,2029.0,0.202,0.710,0.035
5,Ward 11,2021,0.093829,0.138123,0.271201,0.496846,0.142296,0.488,0.298,1976.0,2592.0,0.153,0.692,0.073
6,Ward 12,2016,0.116510,0.160466,0.292126,0.430898,0.116201,0.471,0.229,1384.0,2047.0,0.161,0.692,0.047
7,Ward 12,2021,0.076416,0.146727,0.293191,0.483666,0.130109,0.446,0.248,1768.0,2492.0,0.125,0.686,0.085
8,Ward 13,2016,0.208567,0.179245,0.296106,0.316082,0.067564,0.465,0.346,1214.0,1840.0,0.312,0.810,0.074
9,Ward 13,2021,0.141987,0.166305,0.305956,0.385751,0.085259,0.431,0.351,1520.0,2172.0,0.222,0.758,0.140
10,Ward 14,2016,0.120592,0.162693,0.294404,0.422311,0.116489,0.460,0.210,1123.0,1748.0,0.175,0.813,0.084
11,Ward 14,2021,0.075282,0.142152,0.276759,0.505808,0.148665,0.378,0.182,1424.0,2138.0,0.115,0.768,0.124
12,Ward 15,2016,0.084334,0.141279,0.258044,0.516343,0.164326,0.480,0.197,1353.0,2353.0,0.183,0.732,0.039
13,Ward 15,2021,0.051791,0.126148,0.262798,0.559263,0.170558,0.409,0.218,1716.0,2968.0,0.126,0.670,0.074
14,Ward 16,2016,0.131062,0.221643,0.327535,0.319760,0.067816,0.474,0.279,1205.0,1526.0,0.234,0.701,0.135
15,Ward 16,2021,0.069248,0.192934,0.337212,0.400606,0.091531,0.391,0.261,1492.0,1846.0,0.144,0.638,0.213
16,Ward 17,2016,0.124327,0.188705,0.321003,0.365965,0.083248,0.532,0.323,1390.0,1575.0,0.227,0.694,0.113
17,Ward 17,2021,0.070018,0.166836,0.331471,0.431675,0.102968,0.436,0.314,1754.0,1904.0,0.144,0.646,0.184
18,Ward 18,2016,0.160595,0.174652,0.301394,0.363359,0.085803,0.594,0.403,1537.0,1814.0,0.277,0.736,0.083
19,Ward 18,2021,0.090757,0.158472,0.303412,0.447359,0.107947,0.493,0.376,1880.0,2202.0,0.178,0.688,0.152
20,Ward 19,2016,0.121960,0.168498,0.294001,0.415541,0.112953,0.468,0.212,1082.0,1784.0,0.184,0.790,0.087
21,Ward 19,2021,0.070565,0.148915,0.291425,0.489095,0.141295,0.386,0.183,1370.0,2168.0,0.119,0.752,0.134
22,Ward 2,2016,0.066294,0.175341,0.329590,0.428775,0.117027,0.442,0.201,1303.0,1606.0,0.117,0.701,0.089
23,Ward 2,2021,0.037352,0.156153,0.310334,0.496161,0.142613,0.392,0.188,1574.0,1930.0,0.079,0.662,0.141
24,Ward 20,2016,0.148008,0.214333,0.315750,0.321908,0.070703,0.440,0.270,936.0,1560.0,0.236,0.749,0.145
25,Ward 20,2021,0.077850,0.189723,0.325687,0.406741,0.102198,0.323,0.227,1196.0,1872.0,0.139,0.660,0.226
26,Ward 21,2016,0.137598,0.252915,0.328142,0.281345,0.051030,0.443,0.296,1067.0,1377.0,0.224,0.729,0.171
27,Ward 21,2021,0.072293,0.211199,0.346994,0.369514,0.082370,0.358,0.260,1338.0,1668.0,0.133,0.635,0.267
28,Ward 22,2016,0.141465,0.229966,0.318727,0.309842,0.064090,0.474,0.347,1103.0,1371.0,0.233,0.684,0.170
29,Ward 22,2021,0.081699,0.205374,0.326362,0.386565,0.088308,0.360,0.320,1358.0,1640.0,0.147,0.593,0.266
30,Ward 23,2016,0.104043,0.233830,0.339362,0.322766,0.064043,0.458,0.336,1144.0,1384.0,0.206,0.714,0.171
31,Ward 23,2021,0.051195,0.201392,0.340233,0.407180,0.099551,0.333,0.288,1408.0,1636.0,0.118,0.604,0.289
32,Ward 24,2016,0.153668,0.234691,0.318923,0.292718,0.056779,0.449,0.273,950.0,1430.0,0.260,0.695,0.183
33,Ward 24,2021,0.079224,0.207915,0.332725,0.380137,0.088584,0.316,0.254,1197.0,1776.0,0.147,0.615,0.275
34,Ward 25,2016,0.061840,0.197137,0.333988,0.407035,0.097505,0.423,0.243,1097.0,1572.0,0.124,0.746,0.133
35,Ward 25,2021,0.034355,0.169008,0.336051,0.460587,0.136109,0.327,0.207,1362.0,1802.0,0.078,0.658,0.222
36,Ward 3,2016,0.107194,0.171436,0.324099,0.397271,0.101241,0.464,0.241,1229.0,1713.0,0.154,0.771,0.078
37,Ward 3,2021,0.065062,0.145793,0.316566,0.472579,0.124522,0.409,0.247,1592.0,2108.0,0.110,0.726,0.122
38,Ward 4,2016,0.133858,0.173139,0.293996,0.399007,0.105290,0.456,0.220,1174.0,1898.0,0.174,0.801,0.074
39,Ward 4,2021,0.077386,0.150884,0.290468,0.481263,0.132069,0.397,0.203,1492.0,2280.0,0.120,0.758,0.117
40,Ward 5,2016,0.172771,0.246680,0.310010,0.270538,0.047497,0.456,0.279,957.0,1406.0,0.236,0.729,0.183
41,Ward 5,2021,0.092557,0.216718,0.333605,0.357120,0.085659,0.348,0.223,1196.0,1660.0,0.147,0.642,0.270
42,Ward 6,2016,0.131573,0.224307,0.312872,0.331249,0.074203,0.465,0.267,1177.0,1544.0,0.188,0.726,0.131
43,Ward 6,2021,0.072235,0.191365,0.324224,0.412176,0.104568,0.361,0.253,1448.0,1918.0,0.115,0.666,0.206
44,Ward 7,2016,0.165120,0.285576,0.303558,0.245746,0.042150,0.444,0.285,1011.0,1368.0,0.257,0.703,0.223
45,Ward 7,2021,0.086620,0.237003,0.335167,0.341210,0.074068,0.332,0.240,1261.0,1622.0,0.151,0.604,0.331
46,Ward 8,2016,0.094635,0.160179,0.267125,0.478061,0.142676,0.431,0.210,1245.0,2068.0,0.139,0.728,0.058
47,Ward 8,2021,0.060415,0.142895,0.270901,0.525789,0.156446,0.380,0.203,1588.0,2418.0,0.101,0.694,0.100
48,Ward 9,2016,0.125417,0.203490,0.326662,0.344432,0.070567,0.474,0.258,1226.0,1585.0,0.163,0.808,0.110
49,Ward 9,2021,0.071348,0.163661,0.324617,0.440374,0.114968,0.413,0.216,1552.0,1910.0,0.108,0.746,0.167

In [46]:
income_ready = income_wide.melt(
    id_vars=["geography", "year"],
    var_name="metric_name",
    value_name="value"
).assign(source_group="income")

In [105]:
income_ready[income_ready['geography']=='Ward 1']

,geography,year,metric_name,value,source_group
0,Ward 1,2016,pct_low_income,0.122387,income
1,Ward 1,2021,pct_low_income,0.061058,income
50,Ward 1,2016,pct_lower_mid_income,0.254377,income
51,Ward 1,2021,pct_lower_mid_income,0.217239,income
100,Ward 1,2016,pct_mid_income,0.328064,income
101,Ward 1,2021,pct_mid_income,0.338499,income
150,Ward 1,2016,pct_high_income,0.295173,income
151,Ward 1,2021,pct_high_income,0.383204,income
200,Ward 1,2016,pct_very_high_income,0.050399,income
201,Ward 1,2021,pct_very_high_income,0.089766,income
250,Ward 1,2016,pct_renters_30_plus_income_on_shelter,0.428000,income
251,Ward 1,2021,pct_renters_30_plus_income_on_shelter,0.342000,income
300,Ward 1,2016,pct_owners_30_plus_income_on_shelter,0.273000,income
301,Ward 1,2021,pct_owners_30_plus_income_on_shelter,0.235000,income
350,Ward 1,2016,avg_rent_cost,1064.000000,income
351,Ward 1,2021,avg_rent_cost,1328.000000,income
400,Ward 1,2016,avg_owner_cost,1425.000000,income
401,Ward 1,2021,avg_owner_cost,1664.000000,income
450,Ward 1,2016,pct_low_income_lim_at,0.225000,income
451,Ward 1,2021,pct_low_income_lim_at,0.129000,income
500,Ward 1,2016,pct_employment_income,0.718000,income
501,Ward 1,2021,pct_employment_income,0.620000,income
550,Ward 1,2016,pct_government_transfers,0.193000,income
551,Ward 1,2021,pct_government_transfers,0.292000,income

## Labour Transformations 7/8
labour_long

In [91]:
labour = data['labour_long']

In [85]:
labour

,variable,geography,value,year,category
0,Total - Population aged 15 years and over by L...,Toronto,2294785.0,2016,labour
1,In the labour force,Toronto,1483680.0,2016,labour
2,Employed,Toronto,1361375.0,2016,labour
3,Unemployed,Toronto,122305.0,2016,labour
4,Not in the labour force,Toronto,811110.0,2016,labour
...,...,...,...,...,...
1217,Total - Place of work status for the employed ...,Ward 25,48605.0,2016,labour
1218,Worked at home,Ward 25,2310.0,2016,labour
1219,Worked outside Canada,Ward 25,240.0,2016,labour
1220,No fixed workplace address,Ward 25,5360.0,2016,labour
1221,Worked at usual place,Ward 25,40700.0,2016,labour

In [86]:
labour_d = drop_totals(labour)
print(ds.quick_summary(labour))

             dtype  col_index  missing_pct  n_unique
variable    object          0          0.0        42
geography   object          1          0.0        25
value      float64          2          0.0       821
year         int64          3          0.0         1
category    object          4          0.0         1

In [88]:
labour_d[labour_d['value'].isnull()]

Empty DataFrame
Columns: [variable, geography, value, year, category]
Index: []

In [89]:
#labour[labour['variable']]
labour_d['variable'].value_counts()

variable
Participation rate                                                               50
In the labour force                                                              25
61 Educational services                                                          25
44-45 Retail trade                                                               25
48-49 Transportation and warehousing                                             25
51 Information and cultural industries                                           25
52 Finance and insurance                                                         25
53 Real estate and rental and leasing                                            25
54 Professional, scientific and technical services                               25
55 Management of companies and enterprises                                       25
56 Administrative and support, waste management and remediation services         25
62 Health care and social assistance                                             25
31-33 Manufacturing                                                              25
71 Arts, entertainment and recreation                                            25
72 Accommodation and food services                                               25
81 Other services (except public administration)                                 25
91 Public administration                                                         25
Worked at home                                                                   25
Worked outside Canada                                                            25
No fixed workplace address                                                       25
41 Wholesale trade                                                               25
23 Construction                                                                  25
Employed                                                                         25
22 Utilities                                                                     25
Unemployed                                                                       25
Not in the labour force                                                          25
Unemployment rate                                                                25
All occupations                                                                  25
0 Management occupations                                                         25
1 Business, finance and administration occupations                               25
2 Natural and applied sciences and related occupations                           25
3 Health occupations                                                             25
4 Occupations in education, law and social, community and government services    25
5 Occupations in art, culture, recreation and sport                              25
6 Sales and service occupations                                                  25
7 Trades, transport and equipment operators and related occupations              25
8 Natural resources, agriculture and related production occupations              25
9 Occupations in manufacturing and utilities                                     25
All industry categories                                                          25
11 Agriculture, forestry, fishing and hunting                                    25
21 Mining, quarrying, and oil and gas extraction                                 25
Worked at usual place                                                            25
Name: count, dtype: int64

In [92]:
a = [labour['variable'].isin(['In the labour force','Employed','Unemployed', 'Not in the labour force', 'Participation rate','Unemployment rate'])]
a = a[a['geography']=='Ward 1']

In [95]:
a

                   variable geography    value  year category
48      In the labour force    Ward 1  57310.0  2016   labour
49                 Employed    Ward 1  51215.0  2016   labour
50               Unemployed    Ward 1   6095.0  2016   labour
51  Not in the labour force    Ward 1  37985.0  2016   labour
52        Unemployment rate    Ward 1     10.6  2016   labour
54       Participation rate    Ward 1     65.2  2016   labour
56       Participation rate    Ward 1     55.3  2016   labour

In [94]:
labour[labour['geography']=='Ward 1']

,variable,geography,value,year,category
47,Total - Population aged 15 years and over by L...,Ward 1,95290.0,2016,labour
48,In the labour force,Ward 1,57310.0,2016,labour
49,Employed,Ward 1,51215.0,2016,labour
50,Unemployed,Ward 1,6095.0,2016,labour
51,Not in the labour force,Ward 1,37985.0,2016,labour
52,Unemployment rate,Ward 1,10.6,2016,labour
53,Total - Males aged 15 years and over by Labour...,Ward 1,NaN,2016,labour
54,Participation rate,Ward 1,65.2,2016,labour
55,Total - Females aged 15 years and over by Labo...,Ward 1,NaN,2016,labour
56,Participation rate,Ward 1,55.3,2016,labour
57,All occupations,Ward 1,54885.0,2016,labour
58,0 Management occupations,Ward 1,3135.0,2016,labour
59,"1 Business, finance and administration occupat...",Ward 1,8330.0,2016,labour
60,2 Natural and applied sciences and related occ...,Ward 1,3085.0,2016,labour
61,3 Health occupations,Ward 1,3200.0,2016,labour
62,"4 Occupations in education, law and social, co...",Ward 1,4550.0,2016,labour
63,"5 Occupations in art, culture, recreation and ...",Ward 1,965.0,2016,labour
64,6 Sales and service occupations,Ward 1,15510.0,2016,labour
65,"7 Trades, transport and equipment operators an...",Ward 1,9700.0,2016,labour
66,"8 Natural resources, agriculture and related p...",Ward 1,340.0,2016,labour
67,9 Occupations in manufacturing and utilities,Ward 1,6070.0,2016,labour
68,All industry categories,Ward 1,54890.0,2016,labour
69,"11 Agriculture, forestry, fishing and hunting",Ward 1,75.0,2016,labour
70,"21 Mining, quarrying, and oil and gas extraction",Ward 1,35.0,2016,labour
71,22 Utilities,Ward 1,150.0,2016,labour
72,23 Construction,Ward 1,3835.0,2016,labour
73,31-33 Manufacturing,Ward 1,8315.0,2016,labour
74,41 Wholesale trade,Ward 1,2290.0,2016,labour
75,44-45 Retail trade,Ward 1,6455.0,2016,labour
76,48-49 Transportation and warehousing,Ward 1,5190.0,2016,labour
77,51 Information and cultural industries,Ward 1,1225.0,2016,labour
78,52 Finance and insurance,Ward 1,2290.0,2016,labour
79,53 Real estate and rental and leasing,Ward 1,955.0,2016,labour
80,"54 Professional, scientific and technical serv...",Ward 1,2895.0,2016,labour
81,55 Management of companies and enterprises,Ward 1,75.0,2016,labour
82,"56 Administrative and support, waste managemen...",Ward 1,4265.0,2016,labour
83,61 Educational services,Ward 1,2740.0,2016,labour
84,62 Health care and social assistance,Ward 1,5410.0,2016,labour
85,"71 Arts, entertainment and recreation",Ward 1,960.0,2016,labour
86,72 Accommodation and food services,Ward 1,3985.0,2016,labour
87,81 Other services (except public administration),Ward 1,2275.0,2016,labour
88,91 Public administration,Ward 1,1465.0,2016,labour
89,Total - Place of work status for the employed ...,Ward 1,51215.0,2016,labour
90,Worked at home,Ward 1,1550.0,2016,labour
91,Worked outside Canada,Ward 1,250.0,2016,labour
92,No fixed workplace address,Ward 1,7740.0,2016,labour
93,Worked at usual place,Ward 1,41670.0,2016,labour